template: |
  ## What’s Changed
  $CHANGES

  ## New Contributors
  $CONTRIBUTORS

name-template: 'Release $NEXT_VERSION'
tag-template: '$NEXT_VERSION'
categories: []
change-template: '* $TITLE by @$AUTHOR (#$NUMBER)'
publish: false
target_commitish: main
