#!/usr/bin/env python3
"""
Generated by the declarative model editor
Model id: lorenz
Temporal indexSet: t (default 0..20)

Runtime notes:
- This is an interpreter specialized to the exported model.
- If input tables exist as CSV files named input_<table>.csv next to this script,
  they override the embedded sample table rows.
"""

from __future__ import annotations

import argparse
import csv
import math
import os
from typing import Any, Dict, List, Tuple

# ---- Model metadata (embedded) ----
TEMPORAL_ID = "t"
MODEL_ID = "lorenz"
TEMP_MIN = 0
TEMP_MAX = 20
INDEXSETS = [
  {
    "id": "t",
    "role": "temporal",
    "dataType": "integer",
    "min": "0",
    "max": "20"
  }
]
VAR_DOMAINS: Dict[str, List[str]] = {
  "sigma": [],
  "rho": [],
  "beta": [],
  "x0": [],
  "y0": [],
  "z0": [],
  "dt_min": [],
  "dt_max": [],
  "dt_factor": [],
  "eps": [],
  "tau": [
    "t"
  ],
  "x": [
    "t"
  ],
  "y": [
    "t"
  ],
  "z": [
    "t"
  ],
  "fx": [
    "t"
  ],
  "fy": [
    "t"
  ],
  "fz": [
    "t"
  ],
  "rhs_norm": [
    "t"
  ],
  "dt": [
    "t"
  ],
  "x_half": [
    "t"
  ],
  "y_half": [
    "t"
  ],
  "z_half": [
    "t"
  ],
  "fx_mid": [
    "t"
  ],
  "fy_mid": [
    "t"
  ],
  "fz_mid": [
    "t"
  ]
}
VAR_DEPS: Dict[str, Any] = {
  "sigma": [],
  "rho": [],
  "beta": [],
  "x0": [],
  "y0": [],
  "z0": [],
  "dt_min": [],
  "dt_max": [],
  "dt_factor": [],
  "eps": [],
  "tau": [
    {
      "name": "dt",
      "shift": -1
    },
    {
      "name": "tau",
      "shift": -1
    }
  ],
  "x": [
    {
      "name": "dt",
      "shift": -1
    },
    {
      "name": "fx_mid",
      "shift": -1
    },
    {
      "name": "x",
      "shift": -1
    },
    {
      "name": "x0",
      "shift": 0
    }
  ],
  "y": [
    {
      "name": "dt",
      "shift": -1
    },
    {
      "name": "fy_mid",
      "shift": -1
    },
    {
      "name": "y",
      "shift": -1
    },
    {
      "name": "y0",
      "shift": 0
    }
  ],
  "z": [
    {
      "name": "dt",
      "shift": -1
    },
    {
      "name": "fz_mid",
      "shift": -1
    },
    {
      "name": "z",
      "shift": -1
    },
    {
      "name": "z0",
      "shift": 0
    }
  ],
  "fx": [
    {
      "name": "sigma",
      "shift": 0
    },
    {
      "name": "x",
      "shift": 0
    },
    {
      "name": "y",
      "shift": 0
    }
  ],
  "fy": [
    {
      "name": "rho",
      "shift": 0
    },
    {
      "name": "x",
      "shift": 0
    },
    {
      "name": "y",
      "shift": 0
    },
    {
      "name": "z",
      "shift": 0
    }
  ],
  "fz": [
    {
      "name": "beta",
      "shift": 0
    },
    {
      "name": "x",
      "shift": 0
    },
    {
      "name": "y",
      "shift": 0
    },
    {
      "name": "z",
      "shift": 0
    }
  ],
  "rhs_norm": [
    {
      "name": "fx",
      "shift": 0
    },
    {
      "name": "fy",
      "shift": 0
    },
    {
      "name": "fz",
      "shift": 0
    }
  ],
  "dt": [
    {
      "name": "dt_factor",
      "shift": 0
    },
    {
      "name": "dt_max",
      "shift": 0
    },
    {
      "name": "dt_min",
      "shift": 0
    },
    {
      "name": "eps",
      "shift": 0
    },
    {
      "name": "rhs_norm",
      "shift": 0
    }
  ],
  "x_half": [
    {
      "name": "dt",
      "shift": 0
    },
    {
      "name": "fx",
      "shift": 0
    },
    {
      "name": "x",
      "shift": 0
    }
  ],
  "y_half": [
    {
      "name": "dt",
      "shift": 0
    },
    {
      "name": "fy",
      "shift": 0
    },
    {
      "name": "y",
      "shift": 0
    }
  ],
  "z_half": [
    {
      "name": "dt",
      "shift": 0
    },
    {
      "name": "fz",
      "shift": 0
    },
    {
      "name": "z",
      "shift": 0
    }
  ],
  "fx_mid": [
    {
      "name": "sigma",
      "shift": 0
    },
    {
      "name": "x_half",
      "shift": 0
    },
    {
      "name": "y_half",
      "shift": 0
    }
  ],
  "fy_mid": [
    {
      "name": "rho",
      "shift": 0
    },
    {
      "name": "x_half",
      "shift": 0
    },
    {
      "name": "y_half",
      "shift": 0
    },
    {
      "name": "z_half",
      "shift": 0
    }
  ],
  "fz_mid": [
    {
      "name": "beta",
      "shift": 0
    },
    {
      "name": "x_half",
      "shift": 0
    },
    {
      "name": "y_half",
      "shift": 0
    },
    {
      "name": "z_half",
      "shift": 0
    }
  ]
}
TOPO_VARS: List[str] = [
  "beta",
  "dt_factor",
  "dt_max",
  "dt_min",
  "eps",
  "rho",
  "sigma",
  "tau",
  "x0",
  "x",
  "y0",
  "y",
  "fx",
  "z0",
  "z",
  "fy",
  "fz",
  "rhs_norm",
  "dt",
  "x_half",
  "y_half",
  "fx_mid",
  "z_half",
  "fy_mid",
  "fz_mid"
]
VAR_DEFS: Dict[str, Any] = {
  "sigma": {
    "type": "constant",
    "text": "10",
    "py": "10"
  },
  "rho": {
    "type": "constant",
    "text": "28",
    "py": "28"
  },
  "beta": {
    "type": "constant",
    "text": "2.6666666666666665",
    "py": "2.6666666666666665"
  },
  "x0": {
    "type": "constant",
    "text": "1",
    "py": "1"
  },
  "y0": {
    "type": "constant",
    "text": "1",
    "py": "1"
  },
  "z0": {
    "type": "constant",
    "text": "1",
    "py": "1"
  },
  "dt_min": {
    "type": "constant",
    "text": "0.0005",
    "py": "0.0005"
  },
  "dt_max": {
    "type": "constant",
    "text": "0.02",
    "py": "0.02"
  },
  "dt_factor": {
    "type": "constant",
    "text": "0.02",
    "py": "0.02"
  },
  "eps": {
    "type": "constant",
    "text": "1e-12",
    "py": "1e-12"
  },
  "tau": {
    "type": "piecewise",
    "cases": [
      {
        "when_py": "t == 0",
        "value_py": "0"
      },
      {
        "when_py": "t > 0",
        "value_py": "G(\"tau\", t-1) + G(\"dt\", t-1)"
      }
    ]
  },
  "x": {
    "type": "piecewise",
    "cases": [
      {
        "when_py": "t == 0",
        "value_py": "G(\"x0\")"
      },
      {
        "when_py": "t > 0",
        "value_py": "G(\"x\", t-1) + G(\"fx_mid\", t-1) * G(\"dt\", t-1)"
      }
    ]
  },
  "y": {
    "type": "piecewise",
    "cases": [
      {
        "when_py": "t == 0",
        "value_py": "G(\"y0\")"
      },
      {
        "when_py": "t > 0",
        "value_py": "G(\"y\", t-1) + G(\"fy_mid\", t-1) * G(\"dt\", t-1)"
      }
    ]
  },
  "z": {
    "type": "piecewise",
    "cases": [
      {
        "when_py": "t == 0",
        "value_py": "G(\"z0\")"
      },
      {
        "when_py": "t > 0",
        "value_py": "G(\"z\", t-1) + G(\"fz_mid\", t-1) * G(\"dt\", t-1)"
      }
    ]
  },
  "fx": {
    "type": "expression",
    "text": "sigma * (y(t) - x(t))",
    "py": "G(\"sigma\") * (G(\"y\", t) - G(\"x\", t))"
  },
  "fy": {
    "type": "expression",
    "text": "x(t) * (rho - z(t)) - y(t)",
    "py": "G(\"x\", t) * (G(\"rho\") - G(\"z\", t)) - G(\"y\", t)"
  },
  "fz": {
    "type": "expression",
    "text": "x(t) * y(t) - beta * z(t)",
    "py": "G(\"x\", t) * G(\"y\", t) - G(\"beta\") * G(\"z\", t)"
  },
  "rhs_norm": {
    "type": "expression",
    "text": "(fx(t)^2 + fy(t)^2 + fz(t)^2)^(1/2)",
    "py": "(G(\"fx\", t)**2 + G(\"fy\", t)**2 + G(\"fz\", t)**2)**(1/2)"
  },
  "dt": {
    "type": "piecewise",
    "cases": [
      {
        "when_py": "t == 0",
        "value_py": "0.01"
      },
      {
        "when_py": "t > 0",
        "value_py": "min( G(\"dt_max\"), max( G(\"dt_min\"), G(\"dt_factor\") / max(G(\"eps\"), G(\"rhs_norm\", t)) ) )"
      }
    ]
  },
  "x_half": {
    "type": "expression",
    "text": "x(t) + 0.5 * fx(t) * dt(t)",
    "py": "G(\"x\", t) + 0.5 * G(\"fx\", t) * G(\"dt\", t)"
  },
  "y_half": {
    "type": "expression",
    "text": "y(t) + 0.5 * fy(t) * dt(t)",
    "py": "G(\"y\", t) + 0.5 * G(\"fy\", t) * G(\"dt\", t)"
  },
  "z_half": {
    "type": "expression",
    "text": "z(t) + 0.5 * fz(t) * dt(t)",
    "py": "G(\"z\", t) + 0.5 * G(\"fz\", t) * G(\"dt\", t)"
  },
  "fx_mid": {
    "type": "expression",
    "text": "sigma * (y_half(t) - x_half(t))",
    "py": "G(\"sigma\") * (G(\"y_half\", t) - G(\"x_half\", t))"
  },
  "fy_mid": {
    "type": "expression",
    "text": "x_half(t) * (rho - z_half(t)) - y_half(t)",
    "py": "G(\"x_half\", t) * (G(\"rho\") - G(\"z_half\", t)) - G(\"y_half\", t)"
  },
  "fz_mid": {
    "type": "expression",
    "text": "x_half(t) * y_half(t) - beta * z_half(t)",
    "py": "G(\"x_half\", t) * G(\"y_half\", t) - G(\"beta\") * G(\"z_half\", t)"
  }
}
DEFAULT_TABLES: Dict[str, Any] = {}

def _sanitize_filename(name):
    import re
    s = str(name or 'model')
    s = re.sub(r'[^A-Za-z0-9_\-]', '_', s)
    s = re.sub(r'_+', '_', s).strip('_')
    return s or 'model'

# ---- Runtime helpers ----
# Error visibility: we propagate failures as NaN by default, and optionally fail fast with --strict.
def _coerce_cell(x: str) -> Any:
    s = x.strip()
    if s == '':
        return ''
    # try int, then float; else keep string
    try:
        if s.isdigit() or (s.startswith('-') and s[1:].isdigit()):
            return int(s)
    except Exception:
        pass
    try:
        return float(s)
    except Exception:
        return s

def load_tables_from_csv(base_dir: str, default_tables: Dict[str, Any]) -> Dict[str, Any]:
    tables = {k: {'headers': v['headers'][:], 'rows': [r[:] for r in v['rows']]} for k, v in default_tables.items()}
    for table_id in list(tables.keys()):
        path = os.path.join(base_dir, f'input_{table_id}.csv')
        if not os.path.exists(path):
            continue
        with open(path, newline='') as f:
            rdr = csv.reader(f)
            rows = list(rdr)
        if not rows:
            continue
        headers = rows[0]
        data = []
        for r in rows[1:]:
            if not r or all(c.strip() == '' for c in r):
                continue
            data.append([_coerce_cell(c) for c in r])
        tables[table_id] = {'headers': headers, 'rows': data}
    return tables

def table_get(table: Dict[str, Any], row_key: Any, col_name: str) -> Any:
    headers = table.get('headers') or []
    rows = table.get('rows') or []
    if col_name not in headers:
        raise KeyError(f'Column {col_name} not found in table')
    col_idx = headers.index(col_name)
    # rowIndex is always column 0. Use exact match for non-numeric keys;
    # for numeric keys, use largest row_index <= key (stepwise curve).
    best = None
    for r in rows:
        if len(r) == 0:
            continue
        rk = r[0]
        if isinstance(row_key, (int, float)) and isinstance(rk, (int, float)):
            if rk <= row_key:
                best = r
            else:
                break
        else:
            if rk == row_key:
                best = r
                break
    if best is None:
        return None
    return best[col_idx] if col_idx < len(best) else None

# Evaluation cache: (var_id, idx_tuple) -> value
CACHE: Dict[Tuple[str, Tuple[Any, ...]], Any] = {}
ERRORS: List[Dict[str, Any]] = []
SEEN_ERRORS = set()
STRICT = False

BASE_ENV: Dict[str, Any] = {'math': math, 'G': None, 'min': min, 'max': max, 'abs': abs, 'round': round, 'pow': pow, 'int': int, 'float': float}
# BASE_ENV['G'] will be set after G() is defined.

def _nan() -> float:
    return float('nan')

def _record_error(kind: str, var_id: str, key: Tuple[Any, ...], expr: str, err: Exception) -> None:
    k = (kind, var_id, tuple(key), expr)
    if k in SEEN_ERRORS:
        return
    SEEN_ERRORS.add(k)
    ERRORS.append({'kind': kind, 'var': var_id, 'idx': list(key), 'expr': expr, 'error': repr(err)})

def safe_eval(expr: str, env: Dict[str, Any], *, kind: str, var_id: str, key: Tuple[Any, ...]) -> Any:
    try:
        return eval(expr, {'__builtins__': {}}, env)
    except Exception as e:
        if STRICT:
            raise
        _record_error(kind, var_id, key, expr, e)
        return _nan()

def safe_table_get(table: Dict[str, Any], row_key: Any, col_name: str, *, var_id: str, key: Tuple[Any, ...]) -> Any:
    try:
        return table_get(table, row_key, col_name)
    except Exception as e:
        if STRICT:
            raise
        _record_error('table_get', var_id, key, f'table_get(..., {row_key}, {col_name})', e)
        return _nan()

def _key_tuple(var_id: str, idx: Dict[str, Any]) -> Tuple[Any, ...]:
    dom = VAR_DOMAINS.get(var_id, [])
    return tuple(idx.get(d) for d in dom)

def G(var_id: str, *args: Any) -> Any:
    """Non-recursive lookup of a variable value from CACHE.


    Expressions are generated to call G(...). The main loop computes values

    in deterministic topo order per index-point (and per temporal step).

    If a referenced value has not been computed yet, return NaN (and record).
"""
    dom = VAR_DOMAINS.get(var_id, [])
    if len(args) > len(dom):
        raise TypeError(f'{var_id} expects {len(dom)} args, got {len(args)}')
    idx = dict(zip(dom, args))
    kt = tuple(idx.get(d) for d in dom)
    key = (var_id, kt)
    if key in CACHE:
        return CACHE[key]
    # If a scalar (domainless) value is requested before it was computed, compute it lazily.
    if len(dom) == 0:
        val = compute_value(var_id, {})
        if val is None:
            val = _nan()
        # If scalar computed to NaN, record it for visibility.
        if isinstance(val, float) and math.isnan(val):
            _record_error('nan_result', var_id, kt, 'nan', ValueError('scalar evaluated to NaN'))
        CACHE[key] = val
        return val
    if not STRICT:
        _record_error('missing_dep', var_id, kt, 'missing dependency', KeyError('value not computed yet'))
    return _nan()

BASE_ENV['G'] = G

def compute_value(var_id: str, idx: Dict[str, Any]) -> Any:
    """Compute one value for (var_id, idx) WITHOUT recursion."""
    d = VAR_DEFS.get(var_id) or {}
    t = d.get('type')
    key_tuple = _key_tuple(var_id, idx)
    if t in ('constant', 'expression'):
        expr = d.get('py') or '0'
        env = dict(BASE_ENV)
        env.update(idx)
        return safe_eval(expr, env, kind='expr', var_id=var_id, key=key_tuple)
    if t == 'piecewise':
        for c in d.get('cases', []):
            cond = c.get('when_py') or 'False'
            env = dict(BASE_ENV)
            env.update(idx)
            ok = bool(safe_eval(cond, env, kind='pw_cond', var_id=var_id, key=key_tuple))
            if ok:
                rhs = c.get('value_py') or '0'
                return safe_eval(rhs, env, kind='pw_rhs', var_id=var_id, key=key_tuple)
        return _nan()
    if t == 'table':
        table_id = d.get('table')
        col = d.get('column')
        table = TABLES.get(table_id) if table_id else None
        if not table or not col:
            return _nan()
        dom = VAR_DOMAINS.get(var_id, [])
        row_key = idx.get(dom[0]) if dom else None
        return safe_table_get(table, row_key, col, var_id=var_id, key=key_tuple)
    if t == 'tableLookup':
        table_id = d.get('table')
        row_ref = d.get('row')
        col_sel = d.get('columnSelector')
        table = TABLES.get(table_id) if table_id else None
        if not table:
            return _nan()
        if row_ref:
            row_key = G(row_ref, *[idx.get(a) for a in VAR_DOMAINS.get(row_ref, [])])
        else:
            row_key = idx.get(TEMPORAL_ID)
        if col_sel:
            col_name = G(col_sel, *[idx.get(a) for a in VAR_DOMAINS.get(col_sel, [])])
            return safe_table_get(table, row_key, str(col_name), var_id=var_id, key=key_tuple)
        headers = table.get('headers') or []
        if len(headers) < 2:
            return _nan()
        return safe_table_get(table, row_key, headers[1], var_id=var_id, key=key_tuple)
    return _nan()

def compute_point(idx: Dict[str, Any]) -> None:
    """Compute all variables for this exact index-point (including current temporal step)

    in deterministic topo order, without recursion."""
    # Ensure shifted deps that go out of temporal range are visible as NaN
    for var_id in TOPO_VARS:
        dom = VAR_DOMAINS.get(var_id, [])
        kt = _key_tuple(var_id, idx)
        key = (var_id, kt)
        if key in CACHE:
            continue
        # Pre-mark any shifted dependencies that are out-of-range, so G() sees them deterministically
        for dep in VAR_DEPS.get(var_id, []):
            dep_id = dep.get('name')
            shift = int(dep.get('shift') or 0)
            if not dep_id or dep_id == var_id:
                continue
            dep_dom = VAR_DOMAINS.get(dep_id, [])
            if shift != 0 and TEMPORAL_ID in dep_dom:
                dep_idx = dict(idx)
                tval = dep_idx.get(TEMPORAL_ID)
                if tval is None:
                    continue
                dep_idx[TEMPORAL_ID] = tval + shift
                if dep_idx[TEMPORAL_ID] < TEMP_MIN or dep_idx[TEMPORAL_ID] > TEMP_MAX:
                    dep_kt = tuple(dep_idx.get(d) for d in dep_dom)
                    dep_key = (dep_id, dep_kt)
                    if dep_key not in CACHE:
                        if not STRICT:
                            _record_error('dep_oob', dep_id, dep_kt, 'out of range', ValueError('temporal index out of bounds'))
                        CACHE[dep_key] = _nan()
        val = compute_value(var_id, idx)
        if val is None:
            val = _nan()
        # If the result is NaN and no specific error was recorded, record nan_result.
        if isinstance(val, float) and math.isnan(val):
            _record_error('nan_result', var_id, kt, 'nan', ValueError('expression evaluated to NaN'))
        CACHE[key] = val

def index_values(indexset_id: str, TEMP_MAX: int, overrides: Dict[str, List[str]]) -> List[Any]:
    # integer ranges if min/max exist; else use overrides or defaults
    meta = next((x for x in INDEXSETS if x.get('id') == indexset_id), None)
    dt = str((meta or {}).get('dataType') or '').lower()
    if indexset_id == TEMPORAL_ID:
        # always 0..TEMP_MAX
        return list(range(0, TEMP_MAX + 1))
    if dt in ('integer', 'int') and meta and meta.get('min') is not None and meta.get('max') is not None:
        try:
            lo = int(float(meta['min']))
            hi = int(float(meta['max']))
            return list(range(lo, hi + 1))
        except Exception:
            pass
    # If any table uses this indexset as its rowIndex, infer values from that table's first column
    for tid, t in TABLES.items():
        hdr = (t.get('headers') or [])
        if hdr and hdr[0] == indexset_id:
            vals = []
            for r in (t.get('rows') or []):
                if r and r[0] not in vals:
                    vals.append(r[0])
            if vals:
                return vals
    # fallback: overrides from CLI
    if indexset_id in overrides:
        raw = overrides[indexset_id]
        # attempt numeric coercion
        out = []
        for s in raw:
            out.append(_coerce_cell(s))
        return out
    # final fallback
    return [1] if indexset_id.lower() == 'cohort' else ['default']

def main() -> None:
    ap = argparse.ArgumentParser(description='Run exported model')
    ap.add_argument('--steps', type=int, default=20, help='temporal max (inclusive)')
    default_csv = _sanitize_filename(MODEL_ID) + '_out.csv'
    ap.add_argument('--csv', type=str, default=default_csv, help='Output CSV path (default: <model_id>_out.csv)')
    ap.add_argument('--index', action='append', default=[], help='Override index values: --index cohort=1,2 or --index day_type=weekday,weekend')
    ap.add_argument('--strict', action='store_true', help='Fail fast on evaluation errors (instead of returning NaN)')
    # ---- Optional plot GIF output ----
    plot_group = ap.add_mutually_exclusive_group()
    plot_group.add_argument('--plot-traj', dest='plot_traj', action='store_true', help='Generate an animated trajectory GIF after computing results (requires --plot-vars)')
    plot_group.add_argument('--plot-static', dest='plot_static', action='store_true', help='Generate a single-frame (static) trajectory GIF after computing results (requires --plot-vars)')
    default_gif = _sanitize_filename(MODEL_ID) + '.gif'
    ap.add_argument('--gif', type=str, default=default_gif, help='GIF output path (default: <model_id>.gif; only used with --plot-traj/--plot-static)')
    ap.add_argument('--fps', type=int, default=24, help='Frames per second for animated GIF (only used with --plot-traj)')
    ap.add_argument('--dpi', type=int, default=120, help='DPI for GIF rendering')
    ap.add_argument('--plot-vars', dest='plot_vars', type=str, default='', help='Plot specification(s). Format: label:x[,y[,z]];label2:x[,y[,z]]. (1D uses t vs x; 2D uses x,y; 3D uses x,y,z).')
    ap.add_argument('--plot-t', dest='plot_t', type=str, default=TEMPORAL_ID, help='Temporal column to animate over for --plot-vars (defaults to temporal index).')
    ap.add_argument('--plot-step', dest='plot_step', type=int, default=1, help='Frame stride for --plot-traj (use >1 to reduce frames).')
    ap.add_argument('--plot-point', dest='plot_point', action='store_true', help='Draw only the moving point (not the whole tail).')
    ap.add_argument('--plot-head-color', dest='plot_head_color', type=str, default='red', help='Default head color for plotted trajectories.')
    ap.add_argument('--plot-tail-color', dest='plot_tail_color', type=str, default='blue', help='Default tail color for plotted trajectories.')
    ap.add_argument('--plot-head-colors', dest='plot_head_colors', type=str, default='', help='Per-trajectory head colors: label=color,label2=color')
    ap.add_argument('--plot-tail-colors', dest='plot_tail_colors', type=str, default='', help='Per-trajectory tail colors: label=color,label2=color')
    ap.add_argument('--no-model-id-title', action='store_true', help='Suppress model id in plot title (saves space)')
    args = ap.parse_args()

    overrides: Dict[str, List[str]] = {}
    for item in args.index:
        if '=' not in item:
            continue
        k, v = item.split('=', 1)
        overrides[k.strip()] = [x.strip() for x in v.split(',') if x.strip() != '']

    base_dir = os.path.dirname(os.path.abspath(__file__))
    global TABLES
    TABLES = load_tables_from_csv(base_dir, DEFAULT_TABLES)
    global STRICT
    STRICT = bool(args.strict)
    TEMP_MAX = int(args.steps)
    if TEMP_MAX < 0: raise SystemExit('steps must be >= 0')

    # Determine index values for all index sets used by any variable
    used_indexsets = set()
    for dom in VAR_DOMAINS.values():
        for d in dom:
            used_indexsets.add(d)
    idx_vals: Dict[str, List[Any]] = {d: index_values(d, TEMP_MAX, overrides) for d in used_indexsets}

    # Build output columns: all variables (scalar first), then indexed
    # IMPORTANT: compute scalars in deterministic topo order to avoid missing_dep due to alpha ordering
    scalar_vars = [vid for vid in TOPO_VARS if len(VAR_DOMAINS.get(vid, [])) == 0]
    indexed_vars = [vid for vid, dom in VAR_DOMAINS.items() if len(dom) > 0]
    indexed_vars.sort()

    # For CSV output, we emit one row per combination of index values for indexed vars.
    # To keep files manageable, we use the union of domains: one big cartesian product over used_indexsets.
    axis = sorted(list(used_indexsets), key=lambda x: (x != TEMPORAL_ID, x))
    headers = axis + scalar_vars + indexed_vars
    with open(args.csv, 'w', newline='') as f:
        w = csv.writer(f)
        w.writerow(headers)
        # Precompute scalar values once (topo order, no recursion)
        scalar_vals = {}
        for vid in scalar_vars:
            kt = ()
            key = (vid, kt)
            if key not in CACHE:
                CACHE[key] = compute_value(vid, {})
            scalar_vals[vid] = CACHE[key]
        # Cartesian product over axis
        def rec(i: int, cur: Dict[str, Any]):
            if i >= len(axis):
                # Compute all values for this index-point before reading outputs
                compute_point(cur)
                row = [cur.get(a) for a in axis]
                row += [scalar_vals.get(v) for v in scalar_vars]
                for v in indexed_vars:
                    dom = VAR_DOMAINS.get(v, [])
                    kt = tuple(cur.get(d) for d in dom)
                    row.append(CACHE.get((v, kt), float('nan')))
                w.writerow(row)
                return
            a = axis[i]
            for val in idx_vals.get(a, []):
                cur[a] = val
                rec(i + 1, cur)
            cur.pop(a, None)
        rec(0, {})

    print('Encountered 0 evaluation issue(s)'); print(f'Wrote {args.csv}')
    if ERRORS:
        # Emit a compact error report to stderr
        import sys
        sys.stderr.write(f'\nEncountered {len(ERRORS)} evaluation issue(s). Showing first 20:\n')
        for e in ERRORS[:20]:
            sys.stderr.write(
                f"- {e['kind']} var={e['var']} idx={e['idx']} expr={e['expr']} err={e['error']}\n"
            )

    # ---- Plot GIF (optional) ----
    plot_traj = bool(getattr(args, 'plot_traj', False))
    plot_static = bool(getattr(args, 'plot_static', False))
    if plot_traj or plot_static:
        plot_vars = str(getattr(args, 'plot_vars', '')).strip()
        if not plot_vars:
            print('Plot requested but --plot-vars not provided; skipping plot.')
        else:
            try:
                import pandas as pd
                import matplotlib.pyplot as plt
                from matplotlib.animation import FuncAnimation, PillowWriter
            except Exception as e:
                raise SystemExit('Trajectory plotting requires pandas, matplotlib, and Pillow. ' + repr(e))

            # Read only header first (fast) to discover columns, then load only needed columns.
            _all_cols = pd.read_csv(args.csv, nrows=0).columns.tolist()
            df = None  # will be loaded after parsing plot spec
            tcol = str(getattr(args, 'plot_t', TEMPORAL_ID)).strip() or TEMPORAL_ID
            step = max(1, int(getattr(args, 'plot_step', 1)))
            point_only = bool(getattr(args, 'plot_point', False))
            default_head = str(getattr(args, 'plot_head_color', 'red'))
            default_tail = str(getattr(args, 'plot_tail_color', 'blue'))

            if tcol not in _all_cols:
                raise SystemExit(f'Temporal column {tcol} not found. Available: {_all_cols}')

            def _parse_color_map(s: str):
                out = {}
                s = (s or '').strip()
                if not s: return out
                for item in s.split(','):
                    item = item.strip()
                    if not item or '=' not in item: continue
                    k, v = item.split('=', 1)
                    out[k.strip()] = v.strip()
                return out

            head_map = _parse_color_map(str(getattr(args, 'plot_head_colors', '')))
            tail_map = _parse_color_map(str(getattr(args, 'plot_tail_colors', '')))

            def _parse_trajs(spec: str):
                items = [p.strip() for p in spec.split(';') if p.strip()]
                out = []
                for it in items:
                    if ':' in it:
                        label, rhs = it.split(':', 1)
                        label = (label.strip() or 'traj')
                    else:
                        label, rhs = ('traj', it)
                    parts = [q.strip() for q in rhs.split(',') if q.strip()]
                    if len(parts) < 1 or len(parts) > 3:
                        raise SystemExit('Each trajectory must have 1 to 3 coordinates: x[,y[,z]]')
                    out.append((label, parts))
                return out

            trajs = _parse_trajs(plot_vars)

            def _parse_trajs(spec: str):
                items = [p.strip() for p in spec.split(';') if p.strip()]
                out = []
                for it in items:
                    if ':' in it:
                        label, rhs = it.split(':', 1)
                        label = (label.strip() or 'traj')
                    else:
                        label, rhs = ('traj', it)
                    parts = [q.strip() for q in rhs.split(',') if q.strip()]
                    if len(parts) < 1 or len(parts) > 3:
                        raise SystemExit('Each trajectory must have 1 to 3 coordinates: x[,y[,z]]')
                    out.append((label, parts))
                return out

            trajs = _parse_trajs(plot_vars)
            dims = sorted(set(len(parts) for _, parts in trajs))
            if len(dims) != 1:
                raise SystemExit(f'All trajectories must have the same dimensionality (got {dims}). Use z=0 for 2D in 3D, or provide only x for 1D.')
            dim = dims[0]

            _need = {tcol}
            for _label, _parts in trajs:
                for _c in _parts:
                    if _c in _all_cols: _need.add(_c)
            df = pd.read_csv(args.csv, usecols=sorted(_need))

            traj_data = []
            frames = None
            for label, parts in trajs:
                cols = [tcol] + parts
                for c in cols:
                    if c != tcol and c not in _all_cols:
                        try: float(c)
                        except Exception: raise SystemExit(f'Column {c} not found. Available: {_all_cols}')
                dd = df[[c for c in cols if c in df.columns]].copy()
                for c in parts:
                    if c not in dd.columns:
                        dd[c] = float(c)
                dd = dd[[tcol] + parts].dropna().sort_values(tcol)
                dd = dd.groupby(tcol, as_index=False).first()
                if dd.empty: raise SystemExit(f'No data for trajectory {label}')
                if frames is None:
                    frames = dd[tcol].tolist()
                else:
                    dd = dd[dd[tcol].isin(frames)]
                traj_data.append((label, dd, parts))

            frames = traj_data[0][1][tcol].tolist()
            if not frames: raise SystemExit('No frames found')
            frame_idx = list(range(0, len(frames), step))
            if frame_idx[-1] != len(frames) - 1: frame_idx.append(len(frames) - 1)
            if plot_static: frame_idx = [len(frames) - 1]

            out_gif = str(getattr(args, 'gif', 'model.gif'))
            fps = int(getattr(args, 'fps', 24))
            dpi = int(getattr(args, 'dpi', 120))

            if dim == 3:
                from mpl_toolkits.mplot3d import Axes3D  # noqa: F401
                fig = plt.figure()
                ax = fig.add_subplot(111, projection='3d')
            else:
                fig, ax = plt.subplots()

            if dim == 1:
                t_min, t_max = float(min(frames)), float(max(frames))
                y_min = min(float(dd[parts[0]].min()) for _, dd, parts in traj_data)
                y_max = max(float(dd[parts[0]].max()) for _, dd, parts in traj_data)
            elif dim == 2:
                x_min = min(float(dd[parts[0]].min()) for _, dd, parts in traj_data)
                x_max = max(float(dd[parts[0]].max()) for _, dd, parts in traj_data)
                y_min = min(float(dd[parts[1]].min()) for _, dd, parts in traj_data)
                y_max = max(float(dd[parts[1]].max()) for _, dd, parts in traj_data)
            else:
                x_min = min(float(dd[parts[0]].min()) for _, dd, parts in traj_data)
                x_max = max(float(dd[parts[0]].max()) for _, dd, parts in traj_data)
                y_min = min(float(dd[parts[1]].min()) for _, dd, parts in traj_data)
                y_max = max(float(dd[parts[1]].max()) for _, dd, parts in traj_data)
                z_min = min(float(dd[parts[2]].min()) for _, dd, parts in traj_data)
                z_max = max(float(dd[parts[2]].max()) for _, dd, parts in traj_data)

            def draw(i):
                ax.clear()
                j = frame_idx[i]
                t_now = frames[j]
                for label, dd, parts in traj_data:
                    tail_color = tail_map.get(label, default_tail)
                    head_color = head_map.get(label, default_head)
                    seg = dd.iloc[[j]] if point_only else dd.iloc[: j + 1]
                    if dim == 1:
                        if not point_only: ax.plot(seg[tcol].values, seg[parts[0]].values, color=tail_color, linewidth=2, label=label)
                        ax.scatter([dd.iloc[j][tcol]], [dd.iloc[j][parts[0]]], color=head_color, s=60)
                    elif dim == 2:
                        if not point_only: ax.plot(seg[parts[0]].values, seg[parts[1]].values, color=tail_color, linewidth=2, label=label)
                        ax.scatter([dd.iloc[j][parts[0]]], [dd.iloc[j][parts[1]]], color=head_color, s=60)
                    else:
                        if not point_only: ax.plot(seg[parts[0]].values, seg[parts[1]].values, seg[parts[2]].values, color=tail_color, linewidth=2, label=label)
                        ax.scatter([dd.iloc[j][parts[0]]], [dd.iloc[j][parts[1]]], [dd.iloc[j][parts[2]]], color=head_color, s=60)
                if dim == 1:
                    ax.set_xlabel(tcol); ax.set_ylabel(traj_data[0][2][0]); ax.set_xlim(t_min, t_max); ax.set_ylim(y_min, y_max)
                elif dim == 2:
                    ax.set_xlabel(traj_data[0][2][0]); ax.set_ylabel(traj_data[0][2][1]); ax.set_xlim(x_min, x_max); ax.set_ylim(y_min, y_max)
                else:
                    ax.set_xlabel(traj_data[0][2][0]); ax.set_ylabel(traj_data[0][2][1]); ax.set_zlabel(traj_data[0][2][2]); ax.set_xlim(x_min, x_max); ax.set_ylim(y_min, y_max); ax.set_zlim(z_min, z_max)
                try: ax.legend(loc='upper right', fontsize='small')
                except Exception: pass
                if bool(getattr(args, 'no_model_id_title', False)):
                    ax.set_title(f'{tcol}={t_now}')
                else:
                    ax.set_title(f'{MODEL_ID} | {tcol}={t_now}')

            ani = FuncAnimation(fig, draw, frames=len(frame_idx), interval=1000 / max(1, fps), repeat=False)
            ani.save(out_gif, writer=PillowWriter(fps=fps), dpi=dpi)
            plt.close(fig)
            print(f'Saved trajectory GIF to {out_gif}')
if __name__ == '__main__':
    main()