#!/usr/bin/env python3
"""
Generated by the declarative model editor
Model id: annuity-model
Temporal indexSet: step (default 0..11)

Runtime notes:
- This is an interpreter specialized to the exported model.
- If input tables exist as CSV files named input_<table>.csv next to this script,
  they override the embedded sample table rows.
"""

from __future__ import annotations

import argparse
import csv
import math
import os
from typing import Any, Dict, List, Tuple

# ---- Model metadata (embedded) ----
TEMPORAL_ID = "step"
MODEL_ID = "annuity-model"
TEMP_MIN = 0
TEMP_MAX = 11
INDEXSETS = [
  {
    "id": "cohort",
    "role": "",
    "dataType": "[object Object]"
  },
  {
    "id": "age",
    "role": "",
    "dataType": "[object Object]"
  },
  {
    "id": "step",
    "role": "temporal",
    "dataType": "[object Object]"
  }
]
VAR_DOMAINS: Dict[str, List[str]] = {
  "step_length": [],
  "projection_limit": [],
  "within_projection_limit": [
    "step"
  ],
  "annual_annuity_amount": [
    "cohort"
  ],
  "annuity_start_age": [
    "cohort"
  ],
  "current_age": [
    "cohort"
  ],
  "mortality_table": [
    "cohort"
  ],
  "attained_age": [
    "cohort",
    "step"
  ],
  "attained_age_years_floor": [
    "cohort",
    "step"
  ],
  "annual_mortality_rate": [
    "cohort",
    "step"
  ],
  "monthly_survival_rate": [
    "cohort",
    "step"
  ],
  "survival_to_start_of_step": [
    "cohort",
    "step"
  ],
  "payable_at_start_of_step": [
    "cohort",
    "step"
  ],
  "payment_indicator": [
    "cohort",
    "step"
  ],
  "cashflow": [
    "cohort",
    "step"
  ],
  "spot_rate": [
    "step"
  ],
  "discount_factor": [
    "step"
  ],
  "discounted_cashflow": [
    "cohort",
    "step"
  ],
  "years_since_start": [
    "step"
  ],
  "discounted_cashflow_future": [
    "cohort",
    "step"
  ]
}
VAR_DEPS: Dict[str, Any] = {
  "step_length": [],
  "projection_limit": [],
  "within_projection_limit": [
    {
      "name": "projection_limit",
      "shift": 0
    },
    {
      "name": "step_length",
      "shift": 0
    }
  ],
  "annual_annuity_amount": [],
  "annuity_start_age": [],
  "current_age": [],
  "mortality_table": [],
  "attained_age": [
    {
      "name": "current_age",
      "shift": 0
    },
    {
      "name": "step_length",
      "shift": 0
    }
  ],
  "attained_age_years_floor": [
    {
      "name": "attained_age",
      "shift": 0
    }
  ],
  "annual_mortality_rate": [
    {
      "name": "attained_age_years_floor",
      "shift": 0
    },
    {
      "name": "mortality_table",
      "shift": 0
    }
  ],
  "monthly_survival_rate": [
    {
      "name": "annual_mortality_rate",
      "shift": 0
    },
    {
      "name": "step_length",
      "shift": 0
    }
  ],
  "survival_to_start_of_step": [
    {
      "name": "monthly_survival_rate",
      "shift": -1
    },
    {
      "name": "survival_to_start_of_step",
      "shift": -1
    }
  ],
  "payable_at_start_of_step": [
    {
      "name": "annuity_start_age",
      "shift": 0
    },
    {
      "name": "attained_age",
      "shift": 0
    }
  ],
  "payment_indicator": [
    {
      "name": "payable_at_start_of_step",
      "shift": 0
    }
  ],
  "cashflow": [
    {
      "name": "annual_annuity_amount",
      "shift": 0
    },
    {
      "name": "payment_indicator",
      "shift": 0
    },
    {
      "name": "step_length",
      "shift": 0
    },
    {
      "name": "survival_to_start_of_step",
      "shift": 0
    }
  ],
  "spot_rate": [],
  "discount_factor": [
    {
      "name": "spot_rate",
      "shift": 0
    },
    {
      "name": "step_length",
      "shift": 0
    }
  ],
  "discounted_cashflow": [
    {
      "name": "cashflow",
      "shift": 0
    },
    {
      "name": "discount_factor",
      "shift": 0
    }
  ],
  "years_since_start": [
    {
      "name": "step_length",
      "shift": 0
    }
  ],
  "discounted_cashflow_future": [
    {
      "name": "discounted_cashflow",
      "shift": 0
    },
    {
      "name": "discounted_cashflow_future",
      "shift": 1
    },
    {
      "name": "within_projection_limit",
      "shift": 0
    }
  ]
}
TOPO_VARS: List[str] = [
  "annual_annuity_amount",
  "annuity_start_age",
  "current_age",
  "mortality_table",
  "projection_limit",
  "spot_rate",
  "step_length",
  "attained_age",
  "attained_age_years_floor",
  "annual_mortality_rate",
  "discount_factor",
  "monthly_survival_rate",
  "payable_at_start_of_step",
  "payment_indicator",
  "survival_to_start_of_step",
  "cashflow",
  "discounted_cashflow",
  "within_projection_limit",
  "discounted_cashflow_future",
  "years_since_start"
]
VAR_DEFS: Dict[str, Any] = {
  "step_length": {
    "type": "constant",
    "text": "1 / 12",
    "py": "1 / 12"
  },
  "projection_limit": {
    "type": "constant",
    "text": "120",
    "py": "120"
  },
  "within_projection_limit": {
    "type": "expression",
    "text": "step_length * ( step + 1) <= projection_limit",
    "py": "G(\"step_length\") * ( step + 1) <= G(\"projection_limit\")"
  },
  "annual_annuity_amount": {
    "type": "table",
    "table": "cohort_data",
    "column": "annual_annuity_amount"
  },
  "annuity_start_age": {
    "type": "table",
    "table": "cohort_data",
    "column": "annuity_start_age"
  },
  "current_age": {
    "type": "table",
    "table": "cohort_data",
    "column": "current_age"
  },
  "mortality_table": {
    "type": "table",
    "table": "cohort_data",
    "column": "mortality_table"
  },
  "attained_age": {
    "type": "expression",
    "text": "current_age(cohort) + step * step_length",
    "py": "G(\"current_age\", cohort) + step * G(\"step_length\")"
  },
  "attained_age_years_floor": {
    "type": "expression",
    "text": "floor(attained_age(cohort, step))",
    "py": "math.floor(G(\"attained_age\", cohort, step))"
  },
  "annual_mortality_rate": {
    "type": "tableLookup",
    "table": "mortality_rate",
    "row": "attained_age_years_floor",
    "columnSelector": "mortality_table"
  },
  "monthly_survival_rate": {
    "type": "expression",
    "text": "(1 - annual_mortality_rate(cohort, step)) ^ step_length",
    "py": "(1 - G(\"annual_mortality_rate\", cohort, step)) ** G(\"step_length\")"
  },
  "survival_to_start_of_step": {
    "type": "piecewise",
    "cases": [
      {
        "when_py": "step == 0",
        "value_py": "1"
      },
      {
        "when_py": "step > 0",
        "value_py": "G(\"survival_to_start_of_step\", cohort, step - 1) * G(\"monthly_survival_rate\", cohort, step - 1)"
      }
    ]
  },
  "payable_at_start_of_step": {
    "type": "expression",
    "text": "attained_age(cohort, step) >= annuity_start_age(cohort)",
    "py": "G(\"attained_age\", cohort, step) >= G(\"annuity_start_age\", cohort)"
  },
  "payment_indicator": {
    "type": "expression",
    "text": "payable_at_start_of_step(cohort, step) ? 1 : 0",
    "py": "(1 if G(\"payable_at_start_of_step\", cohort, step) else 0)"
  },
  "cashflow": {
    "type": "expression",
    "text": "annual_annuity_amount(cohort) * step_length * payment_indicator(cohort, step) * survival_to_start_of_step(cohort, step)",
    "py": "G(\"annual_annuity_amount\", cohort) * G(\"step_length\") * G(\"payment_indicator\", cohort, step) * G(\"survival_to_start_of_step\", cohort, step)"
  },
  "spot_rate": {
    "type": "table",
    "table": "spot_rate_table",
    "column": "rate"
  },
  "discount_factor": {
    "type": "expression",
    "text": "(1 + spot_rate(step)) ^ (- step * step_length)",
    "py": "(1 + G(\"spot_rate\", step)) ** (- step * G(\"step_length\"))"
  },
  "discounted_cashflow": {
    "type": "expression",
    "text": "cashflow(cohort, step) * discount_factor(step)",
    "py": "G(\"cashflow\", cohort, step) * G(\"discount_factor\", step)"
  },
  "years_since_start": {
    "type": "expression",
    "text": "step * step_length",
    "py": "step * G(\"step_length\")"
  },
  "discounted_cashflow_future": {
    "type": "piecewise",
    "cases": [
      {
        "when_py": "G(\"within_projection_limit\", step)",
        "value_py": "G(\"discounted_cashflow_future\", cohort, step+1) + G(\"discounted_cashflow\", cohort, step)"
      },
      {
        "when_py": "1==1",
        "value_py": "0"
      }
    ]
  }
}
DEFAULT_TABLES: Dict[str, Any] = {
  "cohort_data": {
    "headers": [
      "cohort",
      "annual_annuity_amount",
      "annuity_start_age",
      "current_age",
      "mortality_table"
    ],
    "rows": [
      [
        1,
        12000,
        62,
        61.6,
        "mortality_rate_column1"
      ],
      [
        2,
        12000,
        62,
        67.73333333333333,
        "mortality_rate_column2"
      ],
      [
        3,
        12000,
        62,
        73.86666666666667,
        "mortality_rate_column2"
      ]
    ]
  },
  "mortality_rate": {
    "headers": [
      "age",
      "mortality_rate_column1",
      "mortality_rate_column2"
    ],
    "rows": [
      [
        17,
        0.001,
        0.0015
      ],
      [
        27,
        0.012494252873563219,
        0.012994252873563218
      ],
      [
        36,
        0.02283908045977012,
        0.02333908045977012
      ],
      [
        46,
        0.034333333333333334,
        0.034833333333333334
      ],
      [
        56,
        0.04582758620689656,
        0.04632758620689656
      ],
      [
        65,
        0.05617241379310345,
        0.05667241379310345
      ],
      [
        75,
        0.06766666666666667,
        0.06816666666666667
      ],
      [
        85,
        0.0791609195402299,
        0.0796609195402299
      ],
      [
        94,
        0.08950574712643679,
        0.09000574712643679
      ],
      [
        104,
        0.101,
        0.1015
      ]
    ]
  },
  "spot_rate_table": {
    "headers": [
      "step",
      "rate"
    ],
    "rows": [
      [
        0,
        0.01
      ],
      [
        13,
        0.03333333333333333
      ],
      [
        27,
        0.05666666666666667
      ],
      [
        40,
        0.08
      ],
      [
        53,
        0.10333333333333333
      ],
      [
        67,
        0.12666666666666668
      ],
      [
        80,
        0.15000000000000002
      ],
      [
        93,
        0.17333333333333337
      ],
      [
        107,
        0.19666666666666668
      ],
      [
        120,
        0.22000000000000003
      ]
    ]
  }
}

def _sanitize_filename(name):
    import re
    s = str(name or 'model')
    s = re.sub(r'[^A-Za-z0-9_\-]', '_', s)
    s = re.sub(r'_+', '_', s).strip('_')
    return s or 'model'

# ---- Runtime helpers ----
# Error visibility: we propagate failures as NaN by default, and optionally fail fast with --strict.
def _coerce_cell(x: str) -> Any:
    s = x.strip()
    if s == '':
        return ''
    # try int, then float; else keep string
    try:
        if s.isdigit() or (s.startswith('-') and s[1:].isdigit()):
            return int(s)
    except Exception:
        pass
    try:
        return float(s)
    except Exception:
        return s

def load_tables_from_csv(base_dir: str, default_tables: Dict[str, Any]) -> Tuple[Dict[str, Any], Dict[str, str]]:
    tables = {k: {'headers': v['headers'][:], 'rows': [r[:] for r in v['rows']]} for k, v in default_tables.items()}
    sources: Dict[str, str] = {k: 'embedded' for k in tables}
    for table_id in list(tables.keys()):
        path = os.path.join(base_dir, f'input_{table_id}.csv')
        if not os.path.exists(path):
            continue
        with open(path, newline='') as f:
            rdr = csv.reader(f)
            rows = list(rdr)
        if not rows:
            continue
        headers = rows[0]
        data = []
        for r in rows[1:]:
            if not r or all(c.strip() == '' for c in r):
                continue
            data.append([_coerce_cell(c) for c in r])
        tables[table_id] = {'headers': headers, 'rows': data}
        sources[table_id] = f'csv:{path}'
    return tables, sources

def table_get(table: Dict[str, Any], row_key: Any, col_name: str) -> Any:
    headers = table.get('headers') or []
    rows = table.get('rows') or []
    if col_name not in headers:
        raise KeyError(f'Column {col_name} not found in table')
    col_idx = headers.index(col_name)
    # rowIndex is always column 0. Use exact match for non-numeric keys;
    # for numeric keys, use largest row_index <= key (stepwise curve).
    best = None
    for r in rows:
        if len(r) == 0:
            continue
        rk = r[0]
        if isinstance(row_key, (int, float)) and isinstance(rk, (int, float)):
            if rk <= row_key:
                best = r
            else:
                break
        else:
            if rk == row_key:
                best = r
                break
    if best is None:
        return None
    return best[col_idx] if col_idx < len(best) else None

# Evaluation cache: (var_id, idx_tuple) -> value
CACHE: Dict[Tuple[str, Tuple[Any, ...]], Any] = {}
_G_COMPUTING: set = set()  # re-entrancy guard for circular dep detection
ERRORS: List[Dict[str, Any]] = []
SEEN_ERRORS = set()
STRICT = False
_LOG_LINES: List[str] = []

def _log(msg: str) -> None:
    print(msg)
    _LOG_LINES.append(str(msg))

BASE_ENV: Dict[str, Any] = {'math': math, 'G': None, 'min': min, 'max': max, 'abs': abs, 'round': round, 'pow': pow, 'int': int, 'float': float}
# BASE_ENV['G'] will be set after G() is defined.

def _nan() -> float:
    return float('nan')

def _record_error(kind: str, var_id: str, key: Tuple[Any, ...], expr: str, err: Exception) -> None:
    k = (kind, var_id, tuple(key), expr)
    if k in SEEN_ERRORS:
        return
    SEEN_ERRORS.add(k)
    ERRORS.append({'kind': kind, 'var': var_id, 'idx': list(key), 'expr': expr, 'error': repr(err)})

def safe_eval(expr: str, env: Dict[str, Any], *, kind: str, var_id: str, key: Tuple[Any, ...]) -> Any:
    try:
        return eval(expr, {'__builtins__': {}}, env)
    except Exception as e:
        if STRICT:
            raise
        _record_error(kind, var_id, key, expr, e)
        return _nan()

def safe_table_get(table: Dict[str, Any], row_key: Any, col_name: str, *, var_id: str, key: Tuple[Any, ...]) -> Any:
    try:
        return table_get(table, row_key, col_name)
    except Exception as e:
        if STRICT:
            raise
        _record_error('table_get', var_id, key, f'table_get(..., {row_key}, {col_name})', e)
        return _nan()

def _key_tuple(var_id: str, idx: Dict[str, Any]) -> Tuple[Any, ...]:
    dom = VAR_DOMAINS.get(var_id, [])
    return tuple(idx.get(d) for d in dom)

def G(var_id: str, *args: Any) -> Any:
    """Lookup a variable value from CACHE, computing lazily if needed.


    Expressions call G(...) for variable references. Values are computed in

    topo order per index-point; shifted deps (step+N / step-N) are resolved

    lazily on demand. A re-entrancy guard catches circular dependencies.
"""
    dom = VAR_DOMAINS.get(var_id, [])
    if len(args) > len(dom):
        raise TypeError(f'{var_id} expects {len(dom)} args, got {len(args)}')
    idx = dict(zip(dom, args))
    kt = tuple(idx.get(d) for d in dom)
    key = (var_id, kt)
    if key in CACHE:
        return CACHE[key]
    # Guard against circular dependencies (would otherwise cause infinite recursion).
    if key in _G_COMPUTING:
        if not STRICT:
            _record_error('circular_dep', var_id, kt, 'circular dependency', ValueError('circular dependency detected'))
        return _nan()
    _G_COMPUTING.add(key)
    try:
        val = compute_value(var_id, idx)
        if val is None:
            val = _nan()
        if isinstance(val, float) and math.isnan(val):
            _record_error('nan_result', var_id, kt, 'nan', ValueError('expression evaluated to NaN'))
        CACHE[key] = val
        return val
    finally:
        _G_COMPUTING.discard(key)

BASE_ENV['G'] = G

def G_cache_only(var_id: str, *args: Any) -> Any:
    dom = VAR_DOMAINS.get(var_id, [])
    idx = dict(zip(dom, args))
    kt = tuple(idx.get(d) for d in dom)
    key = (var_id, kt)
    if key in CACHE:
        return CACHE[key]
    return _nan()

def compute_value_no_self(var_id: str, idx: Dict[str, Any]) -> Any:
    d = VAR_DEFS.get(var_id) or {}
    t = d.get('type')
    key_tuple = _key_tuple(var_id, idx)

    env = dict(BASE_ENV)
    env.update(idx)

    def _G(v: str, *a: Any) -> Any:
        if v == var_id:
            return G_cache_only(v, *a)
        return G(v, *a)
    env['G'] = _G

    if t in ('constant', 'expression'):
        expr = d.get('py') or '0'
        return safe_eval(expr, env, kind='expr', var_id=var_id, key=key_tuple)

    if t == 'piecewise':
        for c in d.get('cases', []):
            cond = c.get('when_py') or 'False'
            ok = bool(safe_eval(cond, env, kind='pw_cond', var_id=var_id, key=key_tuple))
            if ok:
                rhs = c.get('value_py') or '0'
                return safe_eval(rhs, env, kind='pw_rhs', var_id=var_id, key=key_tuple)
        return _nan()

    return compute_value(var_id, idx)

def compute_value(var_id: str, idx: Dict[str, Any]) -> Any:
    """Compute one value for (var_id, idx) WITHOUT recursion."""
    d = VAR_DEFS.get(var_id) or {}
    t = d.get('type')
    key_tuple = _key_tuple(var_id, idx)
    if t in ('constant', 'expression'):
        expr = d.get('py') or '0'
        env = dict(BASE_ENV)
        env.update(idx)
        return safe_eval(expr, env, kind='expr', var_id=var_id, key=key_tuple)
    if t == 'piecewise':
        for c in d.get('cases', []):
            cond = c.get('when_py') or 'False'
            env = dict(BASE_ENV)
            env.update(idx)
            ok = bool(safe_eval(cond, env, kind='pw_cond', var_id=var_id, key=key_tuple))
            if ok:
                rhs = c.get('value_py') or '0'
                return safe_eval(rhs, env, kind='pw_rhs', var_id=var_id, key=key_tuple)
        return _nan()
    if t == 'table':
        table_id = d.get('table')
        col = d.get('column')
        table = TABLES.get(table_id) if table_id else None
        if not table or not col:
            return _nan()
        dom = VAR_DOMAINS.get(var_id, [])
        row_key = idx.get(dom[0]) if dom else None
        return safe_table_get(table, row_key, col, var_id=var_id, key=key_tuple)
    if t == 'tableLookup':
        table_id = d.get('table')
        row_ref = d.get('row')
        col_sel = d.get('columnSelector')
        table = TABLES.get(table_id) if table_id else None
        if not table:
            return _nan()
        if row_ref:
            row_key = G(row_ref, *[idx.get(a) for a in VAR_DOMAINS.get(row_ref, [])])
        else:
            row_key = idx.get(TEMPORAL_ID)
        if col_sel:
            col_name = G(col_sel, *[idx.get(a) for a in VAR_DOMAINS.get(col_sel, [])])
            return safe_table_get(table, row_key, str(col_name), var_id=var_id, key=key_tuple)
        headers = table.get('headers') or []
        if len(headers) < 2:
            return _nan()
        return safe_table_get(table, row_key, headers[1], var_id=var_id, key=key_tuple)
    return _nan()

def compute_point(idx: Dict[str, Any]) -> None:
    """Compute all variables for this exact index-point (including current temporal step)

    in deterministic topo order, without recursion."""
    # Ensure shifted deps that go out of temporal range are visible as NaN
    for var_id in TOPO_VARS:
        dom = VAR_DOMAINS.get(var_id, [])
        kt = _key_tuple(var_id, idx)
        key = (var_id, kt)
        if key in CACHE:
            continue
        # Pre-mark any shifted dependencies that are out-of-range, so G() sees them deterministically
        for dep in VAR_DEPS.get(var_id, []):
            dep_id = dep.get('name')
            shift = int(dep.get('shift') or 0)
            if not dep_id or dep_id == var_id:
                continue
            dep_dom = VAR_DOMAINS.get(dep_id, [])
            if shift != 0 and TEMPORAL_ID in dep_dom:
                dep_idx = dict(idx)
                tval = dep_idx.get(TEMPORAL_ID)
                if tval is None:
                    continue
                dep_idx[TEMPORAL_ID] = tval + shift
                if dep_idx[TEMPORAL_ID] < TEMP_MIN or dep_idx[TEMPORAL_ID] > TEMP_MAX:
                    dep_type = (VAR_DEFS.get(dep_id) or {}).get('type')
                    if dep_type in ('table', 'tableLookup'):
                        dep_kt = tuple(dep_idx.get(d) for d in dep_dom)
                        dep_key = (dep_id, dep_kt)
                        if dep_key not in CACHE:
                            if not STRICT:
                                _record_error('dep_oob', dep_id, dep_kt, 'out of range', ValueError('temporal index out of bounds'))
                            CACHE[dep_key] = _nan()
                    # For expression/piecewise/constant deps, allow lazy evaluation beyond TEMP_MAX if requested.
        val = compute_value(var_id, idx)
        if val is None:
            val = _nan()
        # If the result is NaN and no specific error was recorded, record nan_result.
        if isinstance(val, float) and math.isnan(val):
            _record_error('nan_result', var_id, kt, 'nan', ValueError('expression evaluated to NaN'))
        CACHE[key] = val

def index_values(indexset_id: str, TEMP_MAX: int, overrides: Dict[str, List[str]]) -> List[Any]:
    # integer ranges if min/max exist; else use overrides or defaults
    meta = next((x for x in INDEXSETS if x.get('id') == indexset_id), None)
    dt = str((meta or {}).get('dataType') or '').lower()
    if indexset_id == TEMPORAL_ID:
        # always 0..TEMP_MAX
        return list(range(0, TEMP_MAX + 1))
    if dt in ('integer', 'int') and meta and meta.get('min') is not None and meta.get('max') is not None:
        try:
            lo = int(float(meta['min']))
            hi = int(float(meta['max']))
            return list(range(lo, hi + 1))
        except Exception:
            pass
    # Prefer overrides from CLI
    if indexset_id in overrides:
        raw = overrides[indexset_id]
        # attempt numeric coercion
        out = []
        for s in raw:
            out.append(_coerce_cell(s))
        return out
    # If any table uses this indexset as its rowIndex, infer values from that table's first column
    for tid, t in TABLES.items():
        hdr = (t.get('headers') or [])
        if hdr and hdr[0] == indexset_id:
            vals = []
            for r in (t.get('rows') or []):
                if r and r[0] not in vals:
                    vals.append(r[0])
            if vals:
                return vals
    # final fallback
    return [1] if indexset_id.lower() == 'cohort' else ['default']

def main() -> None:
    ap = argparse.ArgumentParser(description='Run exported model')
    ap.add_argument('--steps', type=int, default=11, help='temporal max (inclusive)')
    default_csv = _sanitize_filename(MODEL_ID) + '_out.csv'
    ap.add_argument('--csv', type=str, default=default_csv, help='Output CSV path (default: <model_id>_out.csv)')
    ap.add_argument('--index', action='append', default=[], help='Override index values: --index cohort=1,2 or --index day_type=weekday,weekend')
    ap.add_argument('--strict', action='store_true', help='Fail fast on evaluation errors (instead of returning NaN)')
    # ---- Optional plot GIF output ----
    plot_group = ap.add_mutually_exclusive_group()
    plot_group.add_argument('--plot-traj', dest='plot_traj', action='store_true', help='Generate an animated trajectory GIF after computing results (requires --plot-vars)')
    plot_group.add_argument('--plot-static', dest='plot_static', action='store_true', help='Generate a single-frame (static) trajectory GIF after computing results (requires --plot-vars)')
    default_gif = _sanitize_filename(MODEL_ID) + '.gif'
    ap.add_argument('--gif', type=str, default=default_gif, help='GIF output path (default: <model_id>.gif; only used with --plot-traj/--plot-static)')
    ap.add_argument('--fps', type=int, default=24, help='Frames per second for animated GIF (only used with --plot-traj)')
    ap.add_argument('--dpi', type=int, default=120, help='DPI for GIF rendering')
    ap.add_argument('--plot-vars', dest='plot_vars', type=str, default='', help='Plot specification(s). Format: label:x[,y[,z]];label2:x[,y[,z]]. (1D uses t vs x; 2D uses x,y; 3D uses x,y,z).')
    ap.add_argument('--plot-t', dest='plot_t', type=str, default=TEMPORAL_ID, help='Temporal column to animate over for --plot-vars (defaults to temporal index).')
    ap.add_argument('--plot-title', dest='plot_title', type=str, default='', help='Column to display in the plot title (defaults to --plot-t).')
    ap.add_argument('--plot-step', dest='plot_step', type=int, default=1, help='Frame stride for --plot-traj (use >1 to reduce frames).')
    ap.add_argument('--plot-point', dest='plot_point', action='store_true', help='Draw only the moving point (not the whole tail).')
    ap.add_argument('--plot-head-color', dest='plot_head_color', type=str, default='red', help='Default head color for plotted trajectories.')
    ap.add_argument('--plot-tail-color', dest='plot_tail_color', type=str, default='blue', help='Default tail color for plotted trajectories.')
    ap.add_argument('--plot-head-colors', dest='plot_head_colors', type=str, default='', help='Per-trajectory head colors: label=color,label2=color')
    ap.add_argument('--plot-tail-colors', dest='plot_tail_colors', type=str, default='', help='Per-trajectory tail colors: label=color,label2=color')
    ap.add_argument('--no-model-id-title', action='store_true', help='Suppress model id in plot title (saves space)')
    args = ap.parse_args()

    overrides: Dict[str, List[str]] = {}
    for item in args.index:
        if '=' not in item:
            continue
        k, v = item.split('=', 1)
        overrides[k.strip()] = [x.strip() for x in v.split(',') if x.strip() != '']

    base_dir = os.path.dirname(os.path.abspath(__file__))
    global TABLES
    TABLES, _table_sources = load_tables_from_csv(base_dir, DEFAULT_TABLES)
    if _table_sources:
        _log('Input tables:')
        for _tid, _src in sorted(_table_sources.items()):
            if _src == 'embedded':
                _log(f'  {_tid}: using embedded sample data (no input_{_tid}.csv found)')
            else:
                _log(f'  {_tid}: loaded from {_src}')
    global STRICT
    global TEMP_MAX
    STRICT = bool(args.strict)
    TEMP_MAX = int(args.steps)
    # Increase recursion limit for forward/backward temporal recursions  
    import sys  
    try: 
        sys.setrecursionlimit(max(10000, int(TEMP_MAX) + 5000)) 
    except Exception: 
        pass 
    if TEMP_MAX < 0: raise SystemExit('steps must be >= 0')

    # Determine index values for all index sets used by any variable
    used_indexsets = set()
    for dom in VAR_DOMAINS.values():
        for d in dom:
            used_indexsets.add(d)
    idx_vals: Dict[str, List[Any]] = {d: index_values(d, TEMP_MAX, overrides) for d in used_indexsets}

    # ---- Precompute temporal self-recursive variables iteratively (avoid Python recursion) ----
    # A var is 'temporal self-recursive' if it depends on itself with a non-zero temporal shift.
    temporal_self_vars = []
    for _vid, _deps in (VAR_DEPS or {}).items():
        _self = None
        for _d in (_deps or []):
            if _d.get('name') == _vid and int(_d.get('shift') or 0) != 0:
                _self = _d
                break
        if _self is not None and TEMPORAL_ID in (VAR_DOMAINS.get(_vid, []) or []):
            temporal_self_vars.append((_vid, int(_self.get('shift') or 0)))
    
    if temporal_self_vars:
        _steps = idx_vals.get(TEMPORAL_ID, [])
        # For each such variable, iterate over all combinations of its *non-temporal* domain axes,
        # and compute across step in the correct direction:
        #   shift < 0  (uses step-1) => compute forward in time
        #   shift > 0  (uses step+1) => compute backward in time
        def _iter_combos(_axes, _vals, _i, _cur, _out):
            if _i >= len(_axes):
                _out.append(dict(_cur))
                return
            _a = _axes[_i]
            for _v in _vals.get(_a, []):
                _cur[_a] = _v
                _iter_combos(_axes, _vals, _i + 1, _cur, _out)
            _cur.pop(_a, None)
    
        for _vid, _shift in temporal_self_vars:
            _dom = VAR_DOMAINS.get(_vid, []) or []
            _axes = [d for d in _dom if d != TEMPORAL_ID]
            _combos = []
            _iter_combos(_axes, idx_vals, 0, {}, _combos)
            _ordered_steps = _steps if _shift < 0 else list(reversed(_steps))
            for _base in _combos:
                # Seed boundary for forward recursion (shift > 0):
                # If model wants step+shift but our run horizon stops at TEMP_MAX,
                # assume the value just beyond the horizon is 0 (no future beyond run).
                if _shift > 0:
                    for _k in range(1, _shift + 1):
                        _seed = dict(_base)
                        _seed[TEMPORAL_ID] = TEMP_MAX + _k
                        _seed_kt = tuple(_seed.get(d) for d in _dom)
                        _seed_key = (_vid, _seed_kt)
                        if _seed_key not in CACHE:
                            CACHE[_seed_key] = 0
    
                for _t in _ordered_steps:
                    _idx = dict(_base)
                    _idx[TEMPORAL_ID] = _t
                    _kt = tuple(_idx.get(d) for d in _dom)
                    _key = (_vid, _kt)
                    if _key not in CACHE:
                        CACHE[_key] = compute_value_no_self(_vid, _idx)
    
    # Build output columns: all variables (scalar first), then indexed
    # IMPORTANT: compute scalars in deterministic topo order to avoid missing_dep due to alpha ordering
    scalar_vars = [vid for vid in TOPO_VARS if len(VAR_DOMAINS.get(vid, [])) == 0]
    indexed_vars = [vid for vid, dom in VAR_DOMAINS.items() if len(dom) > 0]
    indexed_vars.sort()

    # For CSV output, we emit one row per combination of index values for indexed vars.
    # To keep files manageable, we use the union of domains: one big cartesian product over used_indexsets.
    axis = sorted(list(used_indexsets), key=lambda x: (x != TEMPORAL_ID, x))
    headers = axis + scalar_vars + indexed_vars
    with open(args.csv, 'w', newline='') as f:
        w = csv.writer(f)
        w.writerow(headers)
        # Precompute scalar values once (topo order, no recursion)
        scalar_vals = {}
        for vid in scalar_vars:
            kt = ()
            key = (vid, kt)
            if key not in CACHE:
                CACHE[key] = compute_value(vid, {})
            scalar_vals[vid] = CACHE[key]
        # Cartesian product over axis
        def rec(i: int, cur: Dict[str, Any]):
            if i >= len(axis):
                # Compute all values for this index-point before reading outputs
                compute_point(cur)
                row = [cur.get(a) for a in axis]
                row += [scalar_vals.get(v) for v in scalar_vars]
                for v in indexed_vars:
                    dom = VAR_DOMAINS.get(v, [])
                    kt = tuple(cur.get(d) for d in dom)
                    row.append(CACHE.get((v, kt), float('nan')))
                w.writerow(row)
                return
            a = axis[i]
            for val in idx_vals.get(a, []):
                cur[a] = val
                rec(i + 1, cur)
            cur.pop(a, None)
        rec(0, {})

    _log(f'Encountered {len(ERRORS)} evaluation issue(s)')
    _log(f'Wrote {args.csv}')
    if ERRORS:
        # Emit a compact error report to stderr
        import sys
        _err_hdr = f'\nEncountered {len(ERRORS)} evaluation issue(s). Showing first 20:'
        sys.stderr.write(_err_hdr + '\n')
        _LOG_LINES.append(_err_hdr.strip())
        for e in ERRORS[:20]:
            _err_line = f"- {e['kind']} var={e['var']} idx={e['idx']} expr={e['expr']} err={e['error']}"
            sys.stderr.write(_err_line + '\n')
            _LOG_LINES.append(_err_line)
    log_path = os.path.splitext(args.csv)[0] + '.log'
    _log(f'Log written to {log_path}')
    with open(log_path, 'w') as _lf:
        _lf.write('\n'.join(_LOG_LINES) + '\n')

    # ---- Plot GIF (optional) ----
    plot_traj = bool(getattr(args, 'plot_traj', False))
    plot_static = bool(getattr(args, 'plot_static', False))
    if plot_traj or plot_static:
        plot_vars = str(getattr(args, 'plot_vars', '')).strip()
        if not plot_vars:
            print('Plot requested but --plot-vars not provided; skipping plot.')
        else:
            try:
                import pandas as pd
                import matplotlib.pyplot as plt
                from matplotlib.animation import FuncAnimation, PillowWriter
            except Exception as e:
                raise SystemExit('Trajectory plotting requires pandas, matplotlib, and Pillow. ' + repr(e))

            # Read only header first (fast) to discover columns, then load only needed columns.
            _all_cols = pd.read_csv(args.csv, nrows=0).columns.tolist()
            df = None  # will be loaded after parsing plot spec
            tcol = str(getattr(args, 'plot_t', TEMPORAL_ID)).strip() or TEMPORAL_ID
            title_col = str(getattr(args, 'plot_title', '')).strip() or tcol
            if title_col not in _all_cols:
                raise SystemExit(f'Title column {title_col} not found. Available: {_all_cols}')
            step = max(1, int(getattr(args, 'plot_step', 1)))
            point_only = bool(getattr(args, 'plot_point', False))
            default_head = str(getattr(args, 'plot_head_color', 'red'))
            default_tail = str(getattr(args, 'plot_tail_color', 'blue'))

            if tcol not in _all_cols:
                raise SystemExit(f'Temporal column {tcol} not found. Available: {_all_cols}')

            def _parse_color_map(s: str):
                out = {}
                s = (s or '').strip()
                if not s: return out
                for item in s.split(','):
                    item = item.strip()
                    if not item or '=' not in item: continue
                    k, v = item.split('=', 1)
                    out[k.strip()] = v.strip()
                return out

            head_map = _parse_color_map(str(getattr(args, 'plot_head_colors', '')))
            tail_map = _parse_color_map(str(getattr(args, 'plot_tail_colors', '')))

            def _parse_trajs(spec: str):
                items = [p.strip() for p in spec.split(';') if p.strip()]
                out = []
                for it in items:
                    if ':' in it:
                        label, rhs = it.split(':', 1)
                        label = (label.strip() or 'traj')
                    else:
                        label, rhs = ('traj', it)
                    parts = [q.strip() for q in rhs.split(',') if q.strip()]
                    if len(parts) < 1 or len(parts) > 3:
                        raise SystemExit('Each trajectory must have 1 to 3 coordinates: x[,y[,z]]')
                    out.append((label, parts))
                return out

            trajs = _parse_trajs(plot_vars)

            def _parse_trajs(spec: str):
                items = [p.strip() for p in spec.split(';') if p.strip()]
                out = []
                for it in items:
                    if ':' in it:
                        label, rhs = it.split(':', 1)
                        label = (label.strip() or 'traj')
                    else:
                        label, rhs = ('traj', it)
                    parts = [q.strip() for q in rhs.split(',') if q.strip()]
                    if len(parts) < 1 or len(parts) > 3:
                        raise SystemExit('Each trajectory must have 1 to 3 coordinates: x[,y[,z]]')
                    out.append((label, parts))
                return out

            trajs = _parse_trajs(plot_vars)
            dims = sorted(set(len(parts) for _, parts in trajs))
            if len(dims) != 1:
                raise SystemExit(f'All trajectories must have the same dimensionality (got {dims}). Use z=0 for 2D in 3D, or provide only x for 1D.')
            dim = dims[0]

            _need = {tcol, title_col}
            # If user provided --index filters and those columns exist in the CSV, load them too so we can filter before plotting
            for _k in overrides.keys():
                if _k in _all_cols:
                    _need.add(_k)
            for _label, _parts in trajs:
                for _c in _parts:
                    if _c in _all_cols: _need.add(_c)
            df = pd.read_csv(args.csv, usecols=sorted(_need))

            # Apply --index filters to the plotting dataframe (so plots reflect the same cohort/index slice)
            # This also avoids silently taking the 'first' row when multiple index combinations exist per step.
            def _coerce_override_list(vs):
                out = []
                for s in vs:
                    try:
                        out.append(_coerce_cell(s))
                    except Exception:
                        out.append(s)
                return out
            for _k, _vs in overrides.items():
                if _k in df.columns and _k != tcol:
                    _vals = _coerce_override_list(_vs)
                    if len(_vals) == 1:
                        df = df[df[_k] == _vals[0]]
                    elif len(_vals) > 1:
                        df = df[df[_k].isin(_vals)]

            traj_data = []
            frames = None
            for label, parts in trajs:
                cols = [tcol] + parts
                if title_col not in cols: cols.append(title_col)
                for c in cols:
                    if c != tcol and c not in _all_cols:
                        try: float(c)
                        except Exception: raise SystemExit(f'Column {c} not found. Available: {_all_cols}')
                dd = df[[c for c in cols if c in df.columns]].copy()
                for c in parts:
                    if c not in dd.columns:
                        dd[c] = float(c)
                # Keep title_col too (so we can label frames nicely)
                keep_cols = [tcol] + parts + ([title_col] if title_col not in ([tcol] + parts) else [])
                keep_cols = list(dict.fromkeys(keep_cols))  # dedupe columns
                dd = dd[keep_cols].dropna().sort_values(tcol)
                dd = dd.groupby(tcol, as_index=False).first()
                if dd.empty: raise SystemExit(f'No data for trajectory {label}')
                if frames is None:
                    frames = dd[tcol].tolist()
                else:
                    dd = dd[dd[tcol].isin(frames)]
                traj_data.append((label, dd, parts))

            frames = traj_data[0][1][tcol].tolist()
            if not frames: raise SystemExit('No frames found')

            # Frame selection:
            frames = traj_data[0][1][tcol].tolist()
            if not frames: raise SystemExit('No frames found')
            frame_idx = list(range(0, len(frames), step))
            if frame_idx[-1] != len(frames) - 1: frame_idx.append(len(frames) - 1)
            if plot_static: frame_idx = [len(frames) - 1]

            out_gif = str(getattr(args, 'gif', 'model.gif'))
            fps = int(getattr(args, 'fps', 24))
            dpi = int(getattr(args, 'dpi', 120))

            if dim == 3:
                from mpl_toolkits.mplot3d import Axes3D  # noqa: F401
                fig = plt.figure()
                ax = fig.add_subplot(111, projection='3d')
            else:
                fig, ax = plt.subplots()

            if dim == 1:
                t_min, t_max = float(min(frames)), float(max(frames))
                y_min = min(float(dd[parts[0]].min()) for _, dd, parts in traj_data)
                y_max = max(float(dd[parts[0]].max()) for _, dd, parts in traj_data)
            elif dim == 2:
                x_min = min(float(dd[parts[0]].min()) for _, dd, parts in traj_data)
                x_max = max(float(dd[parts[0]].max()) for _, dd, parts in traj_data)
                y_min = min(float(dd[parts[1]].min()) for _, dd, parts in traj_data)
                y_max = max(float(dd[parts[1]].max()) for _, dd, parts in traj_data)
            else:
                x_min = min(float(dd[parts[0]].min()) for _, dd, parts in traj_data)
                x_max = max(float(dd[parts[0]].max()) for _, dd, parts in traj_data)
                y_min = min(float(dd[parts[1]].min()) for _, dd, parts in traj_data)
                y_max = max(float(dd[parts[1]].max()) for _, dd, parts in traj_data)
                z_min = min(float(dd[parts[2]].min()) for _, dd, parts in traj_data)
                z_max = max(float(dd[parts[2]].max()) for _, dd, parts in traj_data)

            def draw(i):
                ax.clear()
                j = frame_idx[i]
                t_now = frames[j]
                title_now = traj_data[0][1].iloc[j][title_col] if title_col in traj_data[0][1].columns else t_now
                for label, dd, parts in traj_data:
                    tail_color = tail_map.get(label, default_tail)
                    head_color = head_map.get(label, default_head)
                    seg = dd.iloc[[j]] if point_only else dd.iloc[: j + 1]
                    if dim == 1:
                        if not point_only: ax.plot(seg[tcol].values, seg[parts[0]].values, color=tail_color, linewidth=2, label=label)
                        ax.scatter([dd.iloc[j][tcol]], [dd.iloc[j][parts[0]]], color=head_color, s=60)
                    elif dim == 2:
                        if not point_only: ax.plot(seg[parts[0]].values, seg[parts[1]].values, color=tail_color, linewidth=2, label=label)
                        ax.scatter([dd.iloc[j][parts[0]]], [dd.iloc[j][parts[1]]], color=head_color, s=60)
                    else:
                        if not point_only: ax.plot(seg[parts[0]].values, seg[parts[1]].values, seg[parts[2]].values, color=tail_color, linewidth=2, label=label)
                        ax.scatter([dd.iloc[j][parts[0]]], [dd.iloc[j][parts[1]]], [dd.iloc[j][parts[2]]], color=head_color, s=60)
                if dim == 1:
                    ax.set_xlabel(tcol); ax.set_ylabel(traj_data[0][2][0]); ax.set_xlim(t_min, t_max); ax.set_ylim(y_min, y_max)
                elif dim == 2:
                    ax.set_xlabel(traj_data[0][2][0]); ax.set_ylabel(traj_data[0][2][1]); ax.set_xlim(x_min, x_max); ax.set_ylim(y_min, y_max)
                else:
                    ax.set_xlabel(traj_data[0][2][0]); ax.set_ylabel(traj_data[0][2][1]); ax.set_zlabel(traj_data[0][2][2]); ax.set_xlim(x_min, x_max); ax.set_ylim(y_min, y_max); ax.set_zlim(z_min, z_max)
                try: ax.legend(loc='upper right', fontsize='small')
                except Exception: pass
                if bool(getattr(args, 'no_model_id_title', False)):
                    ax.set_title(f'{title_col}={title_now}')
                else:
                    ax.set_title(f'{MODEL_ID} | {title_col}={title_now}')

            ani = FuncAnimation(fig, draw, frames=len(frame_idx), interval=1000 / max(1, fps), repeat=False)
            ani.save(out_gif, writer=PillowWriter(fps=fps), dpi=dpi)
            plt.close(fig)
            print(f'Saved trajectory GIF to {out_gif}')
if __name__ == '__main__':
    main()