#!/usr/bin/env python3
"""
Generated by the declarative model editor
Model id: rocket_with_thrust
Temporal indexSet: t (default 0..20)

Runtime notes:
- This is an interpreter specialized to the exported model.
- If input tables exist as CSV files named input_<table>.csv next to this script,
  they override the embedded sample table rows.
"""

from __future__ import annotations

import argparse
import csv
import math
import os
from typing import Any, Dict, List, Tuple

# ---- Model metadata (embedded) ----
TEMPORAL_ID = "t"
MODEL_ID = "rocket_with_thrust"
TEMP_MIN = 0
TEMP_MAX = 20
INDEXSETS = [
  {
    "id": "t",
    "role": "temporal",
    "dataType": "integer",
    "min": "0",
    "max": "20"
  }
]
VAR_DOMAINS: Dict[str, List[str]] = {
  "altitude0": [],
  "moon_phase0": [],
  "tli_burn_s": [],
  "tli_accel": [],
  "loi_trigger_dist": [],
  "orbit_altitude_target": [],
  "moon_safe_altitude": [],
  "moon_avoid_accel": [],
  "loi_accel_max": [],
  "loi_gain": [],
  "loi_radial_gain": [],
  "dt0": [],
  "dt_min": [],
  "dt_max": [],
  "dt_factor": [],
  "perigee_gate_factor": [],
  "tli_dt_cap": [],
  "loi_dt_cap": [],
  "loi_dt_near_radius": [],
  "mu_earth": [],
  "mu_moon": [],
  "earth_radius": [],
  "moon_radius": [],
  "moon_orbit_radius": [],
  "moon_period_s": [],
  "moon_n": [],
  "x0": [],
  "y0": [],
  "vx0": [],
  "vy0": [],
  "tau": [
    "t"
  ],
  "day": [
    "t"
  ],
  "moon_angle": [
    "t"
  ],
  "moon_x": [
    "t"
  ],
  "moon_y": [
    "t"
  ],
  "moon_vx": [
    "t"
  ],
  "moon_vy": [
    "t"
  ],
  "x": [
    "t"
  ],
  "y": [
    "t"
  ],
  "radius": [
    "t"
  ],
  "perigee_ref": [
    "t"
  ],
  "near_perigee": [
    "t"
  ],
  "speed": [
    "t"
  ],
  "dxm": [
    "t"
  ],
  "dym": [
    "t"
  ],
  "dist_to_moon": [
    "t"
  ],
  "rel_vx": [
    "t"
  ],
  "rel_vy": [
    "t"
  ],
  "rel_speed": [
    "t"
  ],
  "tli_burn_used": [
    "t"
  ],
  "tli_burn_on": [
    "t"
  ],
  "loi_latched": [
    "t"
  ],
  "vhat_x": [
    "t"
  ],
  "vhat_y": [
    "t"
  ],
  "dxm_prev": [
    "t"
  ],
  "dym_prev": [
    "t"
  ],
  "r_moon_prev": [
    "t"
  ],
  "rel_vx_prev": [
    "t"
  ],
  "rel_vy_prev": [
    "t"
  ],
  "a_avoid_x": [
    "t"
  ],
  "a_avoid_y": [
    "t"
  ],
  "moon_avoid_on": [
    "t"
  ],
  "moon_safe_radius": [],
  "r_orbit_target": [],
  "v_circ_target": [],
  "rhat_x": [
    "t"
  ],
  "rhat_y": [
    "t"
  ],
  "that_x": [
    "t"
  ],
  "that_y": [
    "t"
  ],
  "v_tan_prev": [
    "t"
  ],
  "tan_sign": [
    "t"
  ],
  "rel_vx_des": [
    "t"
  ],
  "rel_vy_des": [
    "t"
  ],
  "a_loi_cmd_x": [
    "t"
  ],
  "a_loi_x": [
    "t"
  ],
  "a_loi_cmd_y": [
    "t"
  ],
  "a_loi_y": [
    "t"
  ],
  "a_thrust_x": [
    "t"
  ],
  "a_thrust_y": [
    "t"
  ],
  "is_burning": [
    "t"
  ],
  "tli_remaining": [
    "t"
  ],
  "ax": [
    "t"
  ],
  "ay": [
    "t"
  ],
  "vx_half": [
    "t"
  ],
  "vy_half": [
    "t"
  ],
  "vx": [
    "t"
  ],
  "vy": [
    "t"
  ],
  "dt": [
    "t"
  ],
  "moon_orbit_error": [
    "t"
  ]
}
VAR_DEPS: Dict[str, Any] = {
  "altitude0": [],
  "moon_phase0": [],
  "tli_burn_s": [],
  "tli_accel": [],
  "loi_trigger_dist": [],
  "orbit_altitude_target": [],
  "moon_safe_altitude": [],
  "moon_avoid_accel": [],
  "loi_accel_max": [],
  "loi_gain": [],
  "loi_radial_gain": [],
  "dt0": [],
  "dt_min": [],
  "dt_max": [],
  "dt_factor": [],
  "perigee_gate_factor": [],
  "tli_dt_cap": [],
  "loi_dt_cap": [],
  "loi_dt_near_radius": [],
  "mu_earth": [],
  "mu_moon": [],
  "earth_radius": [],
  "moon_radius": [],
  "moon_orbit_radius": [],
  "moon_period_s": [],
  "moon_n": [
    {
      "name": "moon_period_s",
      "shift": 0
    }
  ],
  "x0": [
    {
      "name": "altitude0",
      "shift": 0
    },
    {
      "name": "earth_radius",
      "shift": 0
    }
  ],
  "y0": [],
  "vx0": [],
  "vy0": [
    {
      "name": "mu_earth",
      "shift": 0
    },
    {
      "name": "x0",
      "shift": 0
    }
  ],
  "tau": [
    {
      "name": "dt",
      "shift": -1
    },
    {
      "name": "tau",
      "shift": -1
    }
  ],
  "day": [
    {
      "name": "tau",
      "shift": 0
    }
  ],
  "moon_angle": [
    {
      "name": "moon_n",
      "shift": 0
    },
    {
      "name": "moon_phase0",
      "shift": 0
    },
    {
      "name": "tau",
      "shift": 0
    }
  ],
  "moon_x": [
    {
      "name": "moon_angle",
      "shift": 0
    },
    {
      "name": "moon_orbit_radius",
      "shift": 0
    }
  ],
  "moon_y": [
    {
      "name": "moon_angle",
      "shift": 0
    },
    {
      "name": "moon_orbit_radius",
      "shift": 0
    }
  ],
  "moon_vx": [
    {
      "name": "moon_angle",
      "shift": 0
    },
    {
      "name": "moon_n",
      "shift": 0
    },
    {
      "name": "moon_orbit_radius",
      "shift": 0
    }
  ],
  "moon_vy": [
    {
      "name": "moon_angle",
      "shift": 0
    },
    {
      "name": "moon_n",
      "shift": 0
    },
    {
      "name": "moon_orbit_radius",
      "shift": 0
    }
  ],
  "x": [
    {
      "name": "dt",
      "shift": -1
    },
    {
      "name": "vx_half",
      "shift": -1
    },
    {
      "name": "x",
      "shift": -1
    },
    {
      "name": "x0",
      "shift": 0
    }
  ],
  "y": [
    {
      "name": "dt",
      "shift": -1
    },
    {
      "name": "vy_half",
      "shift": -1
    },
    {
      "name": "y",
      "shift": -1
    },
    {
      "name": "y0",
      "shift": 0
    }
  ],
  "radius": [
    {
      "name": "x",
      "shift": 0
    },
    {
      "name": "y",
      "shift": 0
    }
  ],
  "perigee_ref": [
    {
      "name": "perigee_ref",
      "shift": -1
    },
    {
      "name": "radius",
      "shift": 0
    },
    {
      "name": "radius",
      "shift": 0
    }
  ],
  "near_perigee": [
    {
      "name": "perigee_gate_factor",
      "shift": 0
    },
    {
      "name": "perigee_ref",
      "shift": -1
    },
    {
      "name": "radius",
      "shift": -1
    }
  ],
  "speed": [
    {
      "name": "vx",
      "shift": 0
    },
    {
      "name": "vy",
      "shift": 0
    }
  ],
  "dxm": [
    {
      "name": "moon_x",
      "shift": 0
    },
    {
      "name": "x",
      "shift": 0
    }
  ],
  "dym": [
    {
      "name": "moon_y",
      "shift": 0
    },
    {
      "name": "y",
      "shift": 0
    }
  ],
  "dist_to_moon": [
    {
      "name": "dxm",
      "shift": 0
    },
    {
      "name": "dym",
      "shift": 0
    }
  ],
  "rel_vx": [
    {
      "name": "moon_vx",
      "shift": 0
    },
    {
      "name": "vx",
      "shift": 0
    }
  ],
  "rel_vy": [
    {
      "name": "moon_vy",
      "shift": 0
    },
    {
      "name": "vy",
      "shift": 0
    }
  ],
  "rel_speed": [
    {
      "name": "rel_vx",
      "shift": 0
    },
    {
      "name": "rel_vy",
      "shift": 0
    }
  ],
  "tli_burn_used": [
    {
      "name": "dt",
      "shift": -1
    },
    {
      "name": "tli_burn_on",
      "shift": 0
    },
    {
      "name": "tli_burn_used",
      "shift": -1
    }
  ],
  "tli_burn_on": [
    {
      "name": "near_perigee",
      "shift": 0
    },
    {
      "name": "tli_burn_s",
      "shift": 0
    },
    {
      "name": "tli_burn_used",
      "shift": -1
    }
  ],
  "loi_latched": [
    {
      "name": "loi_latched",
      "shift": -1
    },
    {
      "name": "loi_trigger_dist",
      "shift": 0
    },
    {
      "name": "r_moon_prev",
      "shift": 0
    }
  ],
  "vhat_x": [
    {
      "name": "speed",
      "shift": -1
    },
    {
      "name": "vx",
      "shift": -1
    },
    {
      "name": "vx0",
      "shift": 0
    },
    {
      "name": "vy0",
      "shift": 0
    }
  ],
  "vhat_y": [
    {
      "name": "speed",
      "shift": -1
    },
    {
      "name": "vx0",
      "shift": 0
    },
    {
      "name": "vy",
      "shift": -1
    },
    {
      "name": "vy0",
      "shift": 0
    }
  ],
  "dxm_prev": [
    {
      "name": "dxm",
      "shift": -1
    },
    {
      "name": "moon_x",
      "shift": 0
    },
    {
      "name": "x0",
      "shift": 0
    }
  ],
  "dym_prev": [
    {
      "name": "dym",
      "shift": -1
    },
    {
      "name": "moon_y",
      "shift": 0
    },
    {
      "name": "y0",
      "shift": 0
    }
  ],
  "r_moon_prev": [
    {
      "name": "dist_to_moon",
      "shift": -1
    },
    {
      "name": "moon_x",
      "shift": 0
    },
    {
      "name": "moon_y",
      "shift": 0
    },
    {
      "name": "x0",
      "shift": 0
    },
    {
      "name": "y0",
      "shift": 0
    }
  ],
  "rel_vx_prev": [
    {
      "name": "moon_vx",
      "shift": 0
    },
    {
      "name": "rel_vx",
      "shift": -1
    },
    {
      "name": "vx0",
      "shift": 0
    }
  ],
  "rel_vy_prev": [
    {
      "name": "moon_vy",
      "shift": 0
    },
    {
      "name": "rel_vy",
      "shift": -1
    },
    {
      "name": "vy0",
      "shift": 0
    }
  ],
  "a_avoid_x": [
    {
      "name": "moon_avoid_accel",
      "shift": 0
    },
    {
      "name": "moon_avoid_on",
      "shift": 0
    },
    {
      "name": "rhat_x",
      "shift": 0
    }
  ],
  "a_avoid_y": [
    {
      "name": "moon_avoid_accel",
      "shift": 0
    },
    {
      "name": "moon_avoid_on",
      "shift": 0
    },
    {
      "name": "rhat_y",
      "shift": 0
    }
  ],
  "moon_avoid_on": [
    {
      "name": "moon_safe_radius",
      "shift": 0
    },
    {
      "name": "r_moon_prev",
      "shift": 0
    }
  ],
  "moon_safe_radius": [
    {
      "name": "moon_radius",
      "shift": 0
    },
    {
      "name": "moon_safe_altitude",
      "shift": 0
    }
  ],
  "r_orbit_target": [
    {
      "name": "moon_radius",
      "shift": 0
    },
    {
      "name": "orbit_altitude_target",
      "shift": 0
    }
  ],
  "v_circ_target": [
    {
      "name": "mu_moon",
      "shift": 0
    },
    {
      "name": "r_orbit_target",
      "shift": 0
    }
  ],
  "rhat_x": [
    {
      "name": "dxm_prev",
      "shift": 0
    },
    {
      "name": "r_moon_prev",
      "shift": 0
    }
  ],
  "rhat_y": [
    {
      "name": "dym_prev",
      "shift": 0
    },
    {
      "name": "r_moon_prev",
      "shift": 0
    }
  ],
  "that_x": [
    {
      "name": "rhat_y",
      "shift": 0
    }
  ],
  "that_y": [
    {
      "name": "rhat_x",
      "shift": 0
    }
  ],
  "v_tan_prev": [
    {
      "name": "rel_vx_prev",
      "shift": 0
    },
    {
      "name": "rel_vy_prev",
      "shift": 0
    },
    {
      "name": "that_x",
      "shift": 0
    },
    {
      "name": "that_y",
      "shift": 0
    }
  ],
  "tan_sign": [
    {
      "name": "v_tan_prev",
      "shift": 0
    }
  ],
  "rel_vx_des": [
    {
      "name": "tan_sign",
      "shift": 0
    },
    {
      "name": "that_x",
      "shift": 0
    },
    {
      "name": "v_circ_target",
      "shift": 0
    }
  ],
  "rel_vy_des": [
    {
      "name": "tan_sign",
      "shift": 0
    },
    {
      "name": "that_y",
      "shift": 0
    },
    {
      "name": "v_circ_target",
      "shift": 0
    }
  ],
  "a_loi_cmd_x": [
    {
      "name": "loi_accel_max",
      "shift": 0
    },
    {
      "name": "loi_gain",
      "shift": 0
    },
    {
      "name": "loi_radial_gain",
      "shift": 0
    },
    {
      "name": "r_moon_prev",
      "shift": 0
    },
    {
      "name": "r_orbit_target",
      "shift": 0
    },
    {
      "name": "rel_vx_des",
      "shift": 0
    },
    {
      "name": "rel_vx_prev",
      "shift": 0
    },
    {
      "name": "rhat_x",
      "shift": 0
    }
  ],
  "a_loi_x": [
    {
      "name": "a_avoid_x",
      "shift": 0
    },
    {
      "name": "a_loi_cmd_x",
      "shift": 0
    }
  ],
  "a_loi_cmd_y": [
    {
      "name": "loi_accel_max",
      "shift": 0
    },
    {
      "name": "loi_gain",
      "shift": 0
    },
    {
      "name": "loi_radial_gain",
      "shift": 0
    },
    {
      "name": "r_moon_prev",
      "shift": 0
    },
    {
      "name": "r_orbit_target",
      "shift": 0
    },
    {
      "name": "rel_vy_des",
      "shift": 0
    },
    {
      "name": "rel_vy_prev",
      "shift": 0
    },
    {
      "name": "rhat_y",
      "shift": 0
    }
  ],
  "a_loi_y": [
    {
      "name": "a_avoid_y",
      "shift": 0
    },
    {
      "name": "a_loi_cmd_y",
      "shift": 0
    }
  ],
  "a_thrust_x": [
    {
      "name": "a_avoid_x",
      "shift": 0
    },
    {
      "name": "a_avoid_x",
      "shift": 0
    },
    {
      "name": "a_loi_x",
      "shift": 0
    },
    {
      "name": "loi_latched",
      "shift": 0
    },
    {
      "name": "tli_accel",
      "shift": 0
    },
    {
      "name": "tli_burn_on",
      "shift": 0
    },
    {
      "name": "vhat_x",
      "shift": 0
    }
  ],
  "a_thrust_y": [
    {
      "name": "a_avoid_y",
      "shift": 0
    },
    {
      "name": "a_avoid_y",
      "shift": 0
    },
    {
      "name": "a_loi_y",
      "shift": 0
    },
    {
      "name": "loi_latched",
      "shift": 0
    },
    {
      "name": "tli_accel",
      "shift": 0
    },
    {
      "name": "tli_burn_on",
      "shift": 0
    },
    {
      "name": "vhat_y",
      "shift": 0
    }
  ],
  "is_burning": [
    {
      "name": "tli_burn_on",
      "shift": 0
    }
  ],
  "tli_remaining": [
    {
      "name": "tli_burn_s",
      "shift": 0
    },
    {
      "name": "tli_burn_used",
      "shift": 0
    }
  ],
  "ax": [
    {
      "name": "a_thrust_x",
      "shift": 0
    },
    {
      "name": "moon_x",
      "shift": 0
    },
    {
      "name": "moon_y",
      "shift": 0
    },
    {
      "name": "mu_earth",
      "shift": 0
    },
    {
      "name": "mu_moon",
      "shift": 0
    },
    {
      "name": "x",
      "shift": 0
    },
    {
      "name": "y",
      "shift": 0
    }
  ],
  "ay": [
    {
      "name": "a_thrust_y",
      "shift": 0
    },
    {
      "name": "moon_x",
      "shift": 0
    },
    {
      "name": "moon_y",
      "shift": 0
    },
    {
      "name": "mu_earth",
      "shift": 0
    },
    {
      "name": "mu_moon",
      "shift": 0
    },
    {
      "name": "x",
      "shift": 0
    },
    {
      "name": "y",
      "shift": 0
    }
  ],
  "vx_half": [
    {
      "name": "ax",
      "shift": 0
    },
    {
      "name": "dt",
      "shift": 0
    },
    {
      "name": "vx",
      "shift": 0
    }
  ],
  "vy_half": [
    {
      "name": "ay",
      "shift": 0
    },
    {
      "name": "dt",
      "shift": 0
    },
    {
      "name": "vy",
      "shift": 0
    }
  ],
  "vx": [
    {
      "name": "ax",
      "shift": 0
    },
    {
      "name": "dt",
      "shift": -1
    },
    {
      "name": "vx_half",
      "shift": -1
    },
    {
      "name": "vx0",
      "shift": 0
    }
  ],
  "vy": [
    {
      "name": "ay",
      "shift": 0
    },
    {
      "name": "dt",
      "shift": -1
    },
    {
      "name": "vy_half",
      "shift": -1
    },
    {
      "name": "vy0",
      "shift": 0
    }
  ],
  "dt": [
    {
      "name": "dt_factor",
      "shift": 0
    },
    {
      "name": "dt_max",
      "shift": 0
    },
    {
      "name": "dt_max",
      "shift": 0
    },
    {
      "name": "dt_max",
      "shift": 0
    },
    {
      "name": "dt_min",
      "shift": 0
    },
    {
      "name": "dt0",
      "shift": 0
    },
    {
      "name": "loi_dt_cap",
      "shift": 0
    },
    {
      "name": "loi_dt_near_radius",
      "shift": 0
    },
    {
      "name": "r_moon_prev",
      "shift": 0
    },
    {
      "name": "radius",
      "shift": -1
    },
    {
      "name": "speed",
      "shift": -1
    },
    {
      "name": "tli_burn_on",
      "shift": 0
    },
    {
      "name": "tli_dt_cap",
      "shift": 0
    }
  ],
  "moon_orbit_error": [
    {
      "name": "dist_to_moon",
      "shift": 0
    },
    {
      "name": "r_orbit_target",
      "shift": 0
    }
  ]
}
TOPO_VARS: List[str] = [
  "altitude0",
  "dt0",
  "dt_factor",
  "dt_max",
  "dt_min",
  "earth_radius",
  "loi_accel_max",
  "loi_dt_cap",
  "loi_dt_near_radius",
  "loi_gain",
  "loi_radial_gain",
  "loi_trigger_dist",
  "moon_avoid_accel",
  "moon_orbit_radius",
  "moon_period_s",
  "moon_n",
  "moon_phase0",
  "moon_radius",
  "moon_safe_altitude",
  "moon_safe_radius",
  "mu_earth",
  "mu_moon",
  "orbit_altitude_target",
  "perigee_gate_factor",
  "near_perigee",
  "r_orbit_target",
  "tau",
  "day",
  "moon_angle",
  "moon_vx",
  "moon_vy",
  "moon_x",
  "moon_y",
  "tli_accel",
  "tli_burn_s",
  "tli_burn_on",
  "is_burning",
  "tli_burn_used",
  "tli_dt_cap",
  "tli_remaining",
  "v_circ_target",
  "vx0",
  "rel_vx_prev",
  "x0",
  "dxm_prev",
  "vy0",
  "rel_vy_prev",
  "vhat_x",
  "vhat_y",
  "x",
  "dxm",
  "y0",
  "dym_prev",
  "r_moon_prev",
  "dt",
  "loi_latched",
  "moon_avoid_on",
  "rhat_x",
  "a_avoid_x",
  "rhat_y",
  "a_avoid_y",
  "that_x",
  "that_y",
  "v_tan_prev",
  "tan_sign",
  "rel_vx_des",
  "a_loi_cmd_x",
  "a_loi_x",
  "a_thrust_x",
  "rel_vy_des",
  "a_loi_cmd_y",
  "a_loi_y",
  "a_thrust_y",
  "y",
  "ax",
  "ay",
  "dym",
  "dist_to_moon",
  "moon_orbit_error",
  "radius",
  "perigee_ref",
  "vx",
  "rel_vx",
  "vx_half",
  "vy",
  "rel_vy",
  "rel_speed",
  "speed",
  "vy_half"
]
VAR_DEFS: Dict[str, Any] = {
  "altitude0": {
    "type": "constant",
    "text": "200",
    "py": "200"
  },
  "moon_phase0": {
    "type": "constant",
    "text": "1.93",
    "py": "1.93"
  },
  "tli_burn_s": {
    "type": "constant",
    "text": "1400",
    "py": "1400"
  },
  "tli_accel": {
    "type": "constant",
    "text": "0.0025",
    "py": "0.0025"
  },
  "loi_trigger_dist": {
    "type": "constant",
    "text": "300000",
    "py": "300000"
  },
  "orbit_altitude_target": {
    "type": "constant",
    "text": "100",
    "py": "100"
  },
  "moon_safe_altitude": {
    "type": "constant",
    "text": "500",
    "py": "500"
  },
  "moon_avoid_accel": {
    "type": "constant",
    "text": "0.05",
    "py": "0.05"
  },
  "loi_accel_max": {
    "type": "constant",
    "text": "0.004",
    "py": "0.004"
  },
  "loi_gain": {
    "type": "constant",
    "text": "0.0025",
    "py": "0.0025"
  },
  "loi_radial_gain": {
    "type": "constant",
    "text": "0.00001",
    "py": "0.00001"
  },
  "dt0": {
    "type": "constant",
    "text": "10",
    "py": "10"
  },
  "dt_min": {
    "type": "constant",
    "text": "1",
    "py": "1"
  },
  "dt_max": {
    "type": "constant",
    "text": "60",
    "py": "60"
  },
  "dt_factor": {
    "type": "constant",
    "text": "30",
    "py": "30"
  },
  "perigee_gate_factor": {
    "type": "constant",
    "text": "1.05",
    "py": "1.05"
  },
  "tli_dt_cap": {
    "type": "constant",
    "text": "5",
    "py": "5"
  },
  "loi_dt_cap": {
    "type": "constant",
    "text": "2",
    "py": "2"
  },
  "loi_dt_near_radius": {
    "type": "constant",
    "text": "75000",
    "py": "75000"
  },
  "mu_earth": {
    "type": "constant",
    "text": "398600.4418",
    "py": "398600.4418"
  },
  "mu_moon": {
    "type": "constant",
    "text": "4902.800066",
    "py": "4902.800066"
  },
  "earth_radius": {
    "type": "constant",
    "text": "6378",
    "py": "6378"
  },
  "moon_radius": {
    "type": "constant",
    "text": "1737.4",
    "py": "1737.4"
  },
  "moon_orbit_radius": {
    "type": "constant",
    "text": "384400",
    "py": "384400"
  },
  "moon_period_s": {
    "type": "constant",
    "text": "2360591.51",
    "py": "2360591.51"
  },
  "moon_n": {
    "type": "expression",
    "text": "2*3.141592653589793 / moon_period_s",
    "py": "2*3.141592653589793 / G(\"moon_period_s\")"
  },
  "x0": {
    "type": "expression",
    "text": "earth_radius + altitude0",
    "py": "G(\"earth_radius\") + G(\"altitude0\")"
  },
  "y0": {
    "type": "constant",
    "text": "0",
    "py": "0"
  },
  "vx0": {
    "type": "constant",
    "text": "0",
    "py": "0"
  },
  "vy0": {
    "type": "expression",
    "text": "(mu_earth / x0)^(1/2)",
    "py": "(G(\"mu_earth\") / G(\"x0\"))**(1/2)"
  },
  "tau": {
    "type": "piecewise",
    "cases": [
      {
        "when_py": "t==0",
        "value_py": "0"
      },
      {
        "when_py": "t>0",
        "value_py": "G(\"tau\", t-1)+G(\"dt\", t-1)"
      }
    ]
  },
  "day": {
    "type": "expression",
    "text": "floor(100*tau(t)/(60*60*24))/100",
    "py": "math.floor(100*G(\"tau\", t)/(60*60*24))/100"
  },
  "moon_angle": {
    "type": "expression",
    "text": "moon_phase0 + moon_n*tau(t)",
    "py": "G(\"moon_phase0\") + G(\"moon_n\")*G(\"tau\", t)"
  },
  "moon_x": {
    "type": "expression",
    "text": "moon_orbit_radius*cos(moon_angle(t))",
    "py": "G(\"moon_orbit_radius\")*math.cos(G(\"moon_angle\", t))"
  },
  "moon_y": {
    "type": "expression",
    "text": "moon_orbit_radius*sin(moon_angle(t))",
    "py": "G(\"moon_orbit_radius\")*math.sin(G(\"moon_angle\", t))"
  },
  "moon_vx": {
    "type": "expression",
    "text": "-moon_orbit_radius*moon_n*sin(moon_angle(t))",
    "py": "-G(\"moon_orbit_radius\")*G(\"moon_n\")*math.sin(G(\"moon_angle\", t))"
  },
  "moon_vy": {
    "type": "expression",
    "text": "moon_orbit_radius*moon_n*cos(moon_angle(t))",
    "py": "G(\"moon_orbit_radius\")*G(\"moon_n\")*math.cos(G(\"moon_angle\", t))"
  },
  "x": {
    "type": "piecewise",
    "cases": [
      {
        "when_py": "t==0",
        "value_py": "G(\"x0\")"
      },
      {
        "when_py": "t>0",
        "value_py": "G(\"x\", t-1)+G(\"vx_half\", t-1)*G(\"dt\", t-1)"
      }
    ]
  },
  "y": {
    "type": "piecewise",
    "cases": [
      {
        "when_py": "t==0",
        "value_py": "G(\"y0\")"
      },
      {
        "when_py": "t>0",
        "value_py": "G(\"y\", t-1)+G(\"vy_half\", t-1)*G(\"dt\", t-1)"
      }
    ]
  },
  "radius": {
    "type": "expression",
    "text": "(x(t)^2+y(t)^2)^(1/2)",
    "py": "(G(\"x\", t)**2+G(\"y\", t)**2)**(1/2)"
  },
  "perigee_ref": {
    "type": "piecewise",
    "cases": [
      {
        "when_py": "t==0",
        "value_py": "G(\"radius\", 0)"
      },
      {
        "when_py": "t>0",
        "value_py": "min(G(\"perigee_ref\", t-1), G(\"radius\", t))"
      }
    ]
  },
  "near_perigee": {
    "type": "piecewise",
    "cases": [
      {
        "when_py": "t==0",
        "value_py": "1"
      },
      {
        "when_py": "G(\"radius\", t-1) <= G(\"perigee_gate_factor\") * G(\"perigee_ref\", t-1)",
        "value_py": "1"
      },
      {
        "when_py": "1==1",
        "value_py": "0"
      }
    ]
  },
  "speed": {
    "type": "expression",
    "text": "(vx(t)^2+vy(t)^2)^(1/2)",
    "py": "(G(\"vx\", t)**2+G(\"vy\", t)**2)**(1/2)"
  },
  "dxm": {
    "type": "expression",
    "text": "x(t)-moon_x(t)",
    "py": "G(\"x\", t)-G(\"moon_x\", t)"
  },
  "dym": {
    "type": "expression",
    "text": "y(t)-moon_y(t)",
    "py": "G(\"y\", t)-G(\"moon_y\", t)"
  },
  "dist_to_moon": {
    "type": "expression",
    "text": "(dxm(t)^2+dym(t)^2)^(1/2)",
    "py": "(G(\"dxm\", t)**2+G(\"dym\", t)**2)**(1/2)"
  },
  "rel_vx": {
    "type": "expression",
    "text": "vx(t)-moon_vx(t)",
    "py": "G(\"vx\", t)-G(\"moon_vx\", t)"
  },
  "rel_vy": {
    "type": "expression",
    "text": "vy(t)-moon_vy(t)",
    "py": "G(\"vy\", t)-G(\"moon_vy\", t)"
  },
  "rel_speed": {
    "type": "expression",
    "text": "(rel_vx(t)^2+rel_vy(t)^2)^(1/2)",
    "py": "(G(\"rel_vx\", t)**2+G(\"rel_vy\", t)**2)**(1/2)"
  },
  "tli_burn_used": {
    "type": "piecewise",
    "cases": [
      {
        "when_py": "t==0",
        "value_py": "0"
      },
      {
        "when_py": "t>0",
        "value_py": "G(\"tli_burn_used\", t-1) + G(\"tli_burn_on\", t)*G(\"dt\", t-1)"
      }
    ]
  },
  "tli_burn_on": {
    "type": "piecewise",
    "cases": [
      {
        "when_py": "t==0",
        "value_py": "1"
      },
      {
        "when_py": "G(\"tli_burn_used\", t-1) >= G(\"tli_burn_s\")",
        "value_py": "0"
      },
      {
        "when_py": "G(\"near_perigee\", t)==1",
        "value_py": "1"
      },
      {
        "when_py": "1==1",
        "value_py": "0"
      }
    ]
  },
  "loi_latched": {
    "type": "piecewise",
    "cases": [
      {
        "when_py": "t==0",
        "value_py": "0"
      },
      {
        "when_py": "G(\"loi_latched\", t-1)==1",
        "value_py": "1"
      },
      {
        "when_py": "G(\"r_moon_prev\", t)<G(\"loi_trigger_dist\")",
        "value_py": "1"
      },
      {
        "when_py": "1==1",
        "value_py": "0"
      }
    ]
  },
  "vhat_x": {
    "type": "piecewise",
    "cases": [
      {
        "when_py": "t==0",
        "value_py": "G(\"vx0\")/max(0.000001,(G(\"vx0\")**2+G(\"vy0\")**2)**(1/2))"
      },
      {
        "when_py": "t>0",
        "value_py": "G(\"vx\", t-1)/max(0.000001,G(\"speed\", t-1))"
      }
    ]
  },
  "vhat_y": {
    "type": "piecewise",
    "cases": [
      {
        "when_py": "t==0",
        "value_py": "G(\"vy0\")/max(0.000001,(G(\"vx0\")**2+G(\"vy0\")**2)**(1/2))"
      },
      {
        "when_py": "t>0",
        "value_py": "G(\"vy\", t-1)/max(0.000001,G(\"speed\", t-1))"
      }
    ]
  },
  "dxm_prev": {
    "type": "piecewise",
    "cases": [
      {
        "when_py": "t==0",
        "value_py": "G(\"x0\")-G(\"moon_x\", 0)"
      },
      {
        "when_py": "t>0",
        "value_py": "G(\"dxm\", t-1)"
      }
    ]
  },
  "dym_prev": {
    "type": "piecewise",
    "cases": [
      {
        "when_py": "t==0",
        "value_py": "G(\"y0\")-G(\"moon_y\", 0)"
      },
      {
        "when_py": "t>0",
        "value_py": "G(\"dym\", t-1)"
      }
    ]
  },
  "r_moon_prev": {
    "type": "piecewise",
    "cases": [
      {
        "when_py": "t==0",
        "value_py": "((G(\"x0\")-G(\"moon_x\", 0))**2+(G(\"y0\")-G(\"moon_y\", 0))**2)**(1/2)"
      },
      {
        "when_py": "t>0",
        "value_py": "G(\"dist_to_moon\", t-1)"
      }
    ]
  },
  "rel_vx_prev": {
    "type": "piecewise",
    "cases": [
      {
        "when_py": "t==0",
        "value_py": "G(\"vx0\")-G(\"moon_vx\", 0)"
      },
      {
        "when_py": "t>0",
        "value_py": "G(\"rel_vx\", t-1)"
      }
    ]
  },
  "rel_vy_prev": {
    "type": "piecewise",
    "cases": [
      {
        "when_py": "t==0",
        "value_py": "G(\"vy0\")-G(\"moon_vy\", 0)"
      },
      {
        "when_py": "t>0",
        "value_py": "G(\"rel_vy\", t-1)"
      }
    ]
  },
  "a_avoid_x": {
    "type": "expression",
    "text": "moon_avoid_accel * moon_avoid_on(t) * rhat_x(t)",
    "py": "G(\"moon_avoid_accel\") * G(\"moon_avoid_on\", t) * G(\"rhat_x\", t)"
  },
  "a_avoid_y": {
    "type": "expression",
    "text": "moon_avoid_accel * moon_avoid_on(t) * rhat_y(t)",
    "py": "G(\"moon_avoid_accel\") * G(\"moon_avoid_on\", t) * G(\"rhat_y\", t)"
  },
  "moon_avoid_on": {
    "type": "piecewise",
    "cases": [
      {
        "when_py": "G(\"r_moon_prev\", t) < G(\"moon_safe_radius\")",
        "value_py": "1"
      },
      {
        "when_py": "1==1",
        "value_py": "0"
      }
    ]
  },
  "moon_safe_radius": {
    "type": "expression",
    "text": "moon_radius + moon_safe_altitude",
    "py": "G(\"moon_radius\") + G(\"moon_safe_altitude\")"
  },
  "r_orbit_target": {
    "type": "expression",
    "text": "moon_radius + orbit_altitude_target",
    "py": "G(\"moon_radius\") + G(\"orbit_altitude_target\")"
  },
  "v_circ_target": {
    "type": "expression",
    "text": "(mu_moon / r_orbit_target)^(1/2)",
    "py": "(G(\"mu_moon\") / G(\"r_orbit_target\"))**(1/2)"
  },
  "rhat_x": {
    "type": "expression",
    "text": "dxm_prev(t)/max(0.000001,r_moon_prev(t))",
    "py": "G(\"dxm_prev\", t)/max(0.000001,G(\"r_moon_prev\", t))"
  },
  "rhat_y": {
    "type": "expression",
    "text": "dym_prev(t)/max(0.000001,r_moon_prev(t))",
    "py": "G(\"dym_prev\", t)/max(0.000001,G(\"r_moon_prev\", t))"
  },
  "that_x": {
    "type": "expression",
    "text": "-rhat_y(t)",
    "py": "-G(\"rhat_y\", t)"
  },
  "that_y": {
    "type": "expression",
    "text": "rhat_x(t)",
    "py": "G(\"rhat_x\", t)"
  },
  "v_tan_prev": {
    "type": "expression",
    "text": "rel_vx_prev(t)*that_x(t) + rel_vy_prev(t)*that_y(t)",
    "py": "G(\"rel_vx_prev\", t)*G(\"that_x\", t) + G(\"rel_vy_prev\", t)*G(\"that_y\", t)"
  },
  "tan_sign": {
    "type": "expression",
    "text": "v_tan_prev(t)/max(0.000001,abs(v_tan_prev(t)))",
    "py": "G(\"v_tan_prev\", t)/max(0.000001,abs(G(\"v_tan_prev\", t)))"
  },
  "rel_vx_des": {
    "type": "expression",
    "text": "v_circ_target * tan_sign(t) * that_x(t)",
    "py": "G(\"v_circ_target\") * G(\"tan_sign\", t) * G(\"that_x\", t)"
  },
  "rel_vy_des": {
    "type": "expression",
    "text": "v_circ_target * tan_sign(t) * that_y(t)",
    "py": "G(\"v_circ_target\") * G(\"tan_sign\", t) * G(\"that_y\", t)"
  },
  "a_loi_cmd_x": {
    "type": "expression",
    "text": "min( loi_accel_max, max( -loi_accel_max, loi_gain*(rel_vx_des(t)-rel_vx_prev(t)) + loi_radial_gain*(r_orbit_target - r_moon_prev(t))*rhat_x(t) ) )",
    "py": "min( G(\"loi_accel_max\"), max( -G(\"loi_accel_max\"), G(\"loi_gain\")*(G(\"rel_vx_des\", t)-G(\"rel_vx_prev\", t)) + G(\"loi_radial_gain\")*(G(\"r_orbit_target\") - G(\"r_moon_prev\", t))*G(\"rhat_x\", t) ) )"
  },
  "a_loi_x": {
    "type": "expression",
    "text": "a_loi_cmd_x(t) + a_avoid_x(t)",
    "py": "G(\"a_loi_cmd_x\", t) + G(\"a_avoid_x\", t)"
  },
  "a_loi_cmd_y": {
    "type": "expression",
    "text": "min( loi_accel_max, max( -loi_accel_max, loi_gain*(rel_vy_des(t)-rel_vy_prev(t)) + loi_radial_gain*(r_orbit_target - r_moon_prev(t))*rhat_y(t) ) )",
    "py": "min( G(\"loi_accel_max\"), max( -G(\"loi_accel_max\"), G(\"loi_gain\")*(G(\"rel_vy_des\", t)-G(\"rel_vy_prev\", t)) + G(\"loi_radial_gain\")*(G(\"r_orbit_target\") - G(\"r_moon_prev\", t))*G(\"rhat_y\", t) ) )"
  },
  "a_loi_y": {
    "type": "expression",
    "text": "a_loi_cmd_y(t) + a_avoid_y(t)",
    "py": "G(\"a_loi_cmd_y\", t) + G(\"a_avoid_y\", t)"
  },
  "a_thrust_x": {
    "type": "piecewise",
    "cases": [
      {
        "when_py": "G(\"tli_burn_on\", t)==1",
        "value_py": "G(\"tli_accel\")*G(\"vhat_x\", t)"
      },
      {
        "when_py": "G(\"loi_latched\", t)==1",
        "value_py": "G(\"a_loi_x\", t) + G(\"a_avoid_x\", t)"
      },
      {
        "when_py": "1==1",
        "value_py": "G(\"a_avoid_x\", t)"
      }
    ]
  },
  "a_thrust_y": {
    "type": "piecewise",
    "cases": [
      {
        "when_py": "G(\"tli_burn_on\", t)==1",
        "value_py": "G(\"tli_accel\")*G(\"vhat_y\", t)"
      },
      {
        "when_py": "G(\"loi_latched\", t)==1",
        "value_py": "G(\"a_loi_y\", t) + G(\"a_avoid_y\", t)"
      },
      {
        "when_py": "1==1",
        "value_py": "G(\"a_avoid_y\", t)"
      }
    ]
  },
  "is_burning": {
    "type": "expression",
    "text": "tli_burn_on(t)",
    "py": "G(\"tli_burn_on\", t)"
  },
  "tli_remaining": {
    "type": "expression",
    "text": "tli_burn_s - tli_burn_used(t)",
    "py": "G(\"tli_burn_s\") - G(\"tli_burn_used\", t)"
  },
  "ax": {
    "type": "expression",
    "text": "-mu_earth*x(t)/((x(t)^2+y(t)^2)^(3/2)) -mu_moon*(x(t)-moon_x(t))/(((x(t)-moon_x(t))^2+(y(t)-moon_y(t))^2)^(3/2)) + a_thrust_x(t)",
    "py": "-G(\"mu_earth\")*G(\"x\", t)/((G(\"x\", t)**2+G(\"y\", t)**2)**(3/2)) -G(\"mu_moon\")*(G(\"x\", t)-G(\"moon_x\", t))/(((G(\"x\", t)-G(\"moon_x\", t))**2+(G(\"y\", t)-G(\"moon_y\", t))**2)**(3/2)) + G(\"a_thrust_x\", t)"
  },
  "ay": {
    "type": "expression",
    "text": "-mu_earth*y(t)/((x(t)^2+y(t)^2)^(3/2)) -mu_moon*(y(t)-moon_y(t))/(((x(t)-moon_x(t))^2+(y(t)-moon_y(t))^2)^(3/2)) + a_thrust_y(t)",
    "py": "-G(\"mu_earth\")*G(\"y\", t)/((G(\"x\", t)**2+G(\"y\", t)**2)**(3/2)) -G(\"mu_moon\")*(G(\"y\", t)-G(\"moon_y\", t))/(((G(\"x\", t)-G(\"moon_x\", t))**2+(G(\"y\", t)-G(\"moon_y\", t))**2)**(3/2)) + G(\"a_thrust_y\", t)"
  },
  "vx_half": {
    "type": "expression",
    "text": "vx(t)+0.5*ax(t)*dt(t)",
    "py": "G(\"vx\", t)+0.5*G(\"ax\", t)*G(\"dt\", t)"
  },
  "vy_half": {
    "type": "expression",
    "text": "vy(t)+0.5*ay(t)*dt(t)",
    "py": "G(\"vy\", t)+0.5*G(\"ay\", t)*G(\"dt\", t)"
  },
  "vx": {
    "type": "piecewise",
    "cases": [
      {
        "when_py": "t==0",
        "value_py": "G(\"vx0\")"
      },
      {
        "when_py": "t>0",
        "value_py": "G(\"vx_half\", t-1)+0.5*G(\"ax\", t)*G(\"dt\", t-1)"
      }
    ]
  },
  "vy": {
    "type": "piecewise",
    "cases": [
      {
        "when_py": "t==0",
        "value_py": "G(\"vy0\")"
      },
      {
        "when_py": "t>0",
        "value_py": "G(\"vy_half\", t-1)+0.5*G(\"ay\", t)*G(\"dt\", t-1)"
      }
    ]
  },
  "dt": {
    "type": "piecewise",
    "cases": [
      {
        "when_py": "t==0",
        "value_py": "G(\"dt0\")"
      },
      {
        "when_py": "G(\"tli_burn_on\", t)==1",
        "value_py": "min(G(\"tli_dt_cap\"), G(\"dt_max\"))"
      },
      {
        "when_py": "G(\"r_moon_prev\", t) < G(\"loi_dt_near_radius\")",
        "value_py": "min(G(\"loi_dt_cap\"), G(\"dt_max\"))"
      },
      {
        "when_py": "t>0",
        "value_py": "min(G(\"dt_max\"), max(G(\"dt_min\"), G(\"dt_factor\")*(G(\"radius\", t-1)/max(0.001,G(\"speed\", t-1)))))"
      }
    ]
  },
  "moon_orbit_error": {
    "type": "expression",
    "text": "dist_to_moon(t)-r_orbit_target",
    "py": "G(\"dist_to_moon\", t)-G(\"r_orbit_target\")"
  }
}
DEFAULT_TABLES: Dict[str, Any] = {}

def _sanitize_filename(name):
    import re
    s = str(name or 'model')
    s = re.sub(r'[^A-Za-z0-9_\-]', '_', s)
    s = re.sub(r'_+', '_', s).strip('_')
    return s or 'model'

# ---- Runtime helpers ----
# Error visibility: we propagate failures as NaN by default, and optionally fail fast with --strict.
def _coerce_cell(x: str) -> Any:
    s = x.strip()
    if s == '':
        return ''
    # try int, then float; else keep string
    try:
        if s.isdigit() or (s.startswith('-') and s[1:].isdigit()):
            return int(s)
    except Exception:
        pass
    try:
        return float(s)
    except Exception:
        return s

def load_tables_from_csv(base_dir: str, default_tables: Dict[str, Any]) -> Tuple[Dict[str, Any], Dict[str, str]]:
    tables = {k: {'headers': v['headers'][:], 'rows': [r[:] for r in v['rows']]} for k, v in default_tables.items()}
    sources: Dict[str, str] = {k: 'embedded' for k in tables}
    for table_id in list(tables.keys()):
        path = os.path.join(base_dir, f'input_{table_id}.csv')
        if not os.path.exists(path):
            continue
        with open(path, newline='') as f:
            rdr = csv.reader(f)
            rows = list(rdr)
        if not rows:
            continue
        headers = rows[0]
        data = []
        for r in rows[1:]:
            if not r or all(c.strip() == '' for c in r):
                continue
            data.append([_coerce_cell(c) for c in r])
        tables[table_id] = {'headers': headers, 'rows': data}
        sources[table_id] = f'csv:{path}'
    return tables, sources

def table_get(table: Dict[str, Any], row_key: Any, col_name: str) -> Any:
    headers = table.get('headers') or []
    rows = table.get('rows') or []
    if col_name not in headers:
        raise KeyError(f'Column {col_name} not found in table')
    col_idx = headers.index(col_name)
    # rowIndex is always column 0. Use exact match for non-numeric keys;
    # for numeric keys, use largest row_index <= key (stepwise curve).
    best = None
    for r in rows:
        if len(r) == 0:
            continue
        rk = r[0]
        if isinstance(row_key, (int, float)) and isinstance(rk, (int, float)):
            if rk <= row_key:
                best = r
            else:
                break
        else:
            if rk == row_key:
                best = r
                break
    if best is None:
        return None
    return best[col_idx] if col_idx < len(best) else None

# Evaluation cache: (var_id, idx_tuple) -> value
CACHE: Dict[Tuple[str, Tuple[Any, ...]], Any] = {}
_G_COMPUTING: set = set()  # re-entrancy guard for circular dep detection
ERRORS: List[Dict[str, Any]] = []
SEEN_ERRORS = set()
STRICT = False
_LOG_LINES: List[str] = []

def _log(msg: str) -> None:
    print(msg)
    _LOG_LINES.append(str(msg))

BASE_ENV: Dict[str, Any] = {'math': math, 'G': None, 'min': min, 'max': max, 'abs': abs, 'round': round, 'pow': pow, 'int': int, 'float': float}
# BASE_ENV['G'] will be set after G() is defined.

def _nan() -> float:
    return float('nan')

def _record_error(kind: str, var_id: str, key: Tuple[Any, ...], expr: str, err: Exception) -> None:
    k = (kind, var_id, tuple(key), expr)
    if k in SEEN_ERRORS:
        return
    SEEN_ERRORS.add(k)
    ERRORS.append({'kind': kind, 'var': var_id, 'idx': list(key), 'expr': expr, 'error': repr(err)})

def safe_eval(expr: str, env: Dict[str, Any], *, kind: str, var_id: str, key: Tuple[Any, ...]) -> Any:
    try:
        return eval(expr, {'__builtins__': {}}, env)
    except Exception as e:
        if STRICT:
            raise
        _record_error(kind, var_id, key, expr, e)
        return _nan()

def safe_table_get(table: Dict[str, Any], row_key: Any, col_name: str, *, var_id: str, key: Tuple[Any, ...]) -> Any:
    try:
        return table_get(table, row_key, col_name)
    except Exception as e:
        if STRICT:
            raise
        _record_error('table_get', var_id, key, f'table_get(..., {row_key}, {col_name})', e)
        return _nan()

def _key_tuple(var_id: str, idx: Dict[str, Any]) -> Tuple[Any, ...]:
    dom = VAR_DOMAINS.get(var_id, [])
    return tuple(idx.get(d) for d in dom)

def G(var_id: str, *args: Any) -> Any:
    """Lookup a variable value from CACHE, computing lazily if needed.


    Expressions call G(...) for variable references. Values are computed in

    topo order per index-point; shifted deps (step+N / step-N) are resolved

    lazily on demand. A re-entrancy guard catches circular dependencies.
"""
    dom = VAR_DOMAINS.get(var_id, [])
    if len(args) > len(dom):
        raise TypeError(f'{var_id} expects {len(dom)} args, got {len(args)}')
    idx = dict(zip(dom, args))
    kt = tuple(idx.get(d) for d in dom)
    key = (var_id, kt)
    if key in CACHE:
        return CACHE[key]
    # Guard against circular dependencies (would otherwise cause infinite recursion).
    if key in _G_COMPUTING:
        if not STRICT:
            _record_error('circular_dep', var_id, kt, 'circular dependency', ValueError('circular dependency detected'))
        return _nan()
    _G_COMPUTING.add(key)
    try:
        val = compute_value(var_id, idx)
        if val is None:
            val = _nan()
        if isinstance(val, float) and math.isnan(val):
            _record_error('nan_result', var_id, kt, 'nan', ValueError('expression evaluated to NaN'))
        CACHE[key] = val
        return val
    finally:
        _G_COMPUTING.discard(key)

BASE_ENV['G'] = G

def G_cache_only(var_id: str, *args: Any) -> Any:
    dom = VAR_DOMAINS.get(var_id, [])
    idx = dict(zip(dom, args))
    kt = tuple(idx.get(d) for d in dom)
    key = (var_id, kt)
    if key in CACHE:
        return CACHE[key]
    return _nan()

def compute_value_no_self(var_id: str, idx: Dict[str, Any]) -> Any:
    d = VAR_DEFS.get(var_id) or {}
    t = d.get('type')
    key_tuple = _key_tuple(var_id, idx)

    env = dict(BASE_ENV)
    env.update(idx)

    def _G(v: str, *a: Any) -> Any:
        if v == var_id:
            return G_cache_only(v, *a)
        return G(v, *a)
    env['G'] = _G

    if t in ('constant', 'expression'):
        expr = d.get('py') or '0'
        return safe_eval(expr, env, kind='expr', var_id=var_id, key=key_tuple)

    if t == 'piecewise':
        for c in d.get('cases', []):
            cond = c.get('when_py') or 'False'
            ok = bool(safe_eval(cond, env, kind='pw_cond', var_id=var_id, key=key_tuple))
            if ok:
                rhs = c.get('value_py') or '0'
                return safe_eval(rhs, env, kind='pw_rhs', var_id=var_id, key=key_tuple)
        return _nan()

    return compute_value(var_id, idx)

def compute_value(var_id: str, idx: Dict[str, Any]) -> Any:
    """Compute one value for (var_id, idx) WITHOUT recursion."""
    d = VAR_DEFS.get(var_id) or {}
    t = d.get('type')
    key_tuple = _key_tuple(var_id, idx)
    if t in ('constant', 'expression'):
        expr = d.get('py') or '0'
        env = dict(BASE_ENV)
        env.update(idx)
        return safe_eval(expr, env, kind='expr', var_id=var_id, key=key_tuple)
    if t == 'piecewise':
        for c in d.get('cases', []):
            cond = c.get('when_py') or 'False'
            env = dict(BASE_ENV)
            env.update(idx)
            ok = bool(safe_eval(cond, env, kind='pw_cond', var_id=var_id, key=key_tuple))
            if ok:
                rhs = c.get('value_py') or '0'
                return safe_eval(rhs, env, kind='pw_rhs', var_id=var_id, key=key_tuple)
        return _nan()
    if t == 'table':
        table_id = d.get('table')
        col = d.get('column')
        table = TABLES.get(table_id) if table_id else None
        if not table or not col:
            return _nan()
        dom = VAR_DOMAINS.get(var_id, [])
        row_key = idx.get(dom[0]) if dom else None
        return safe_table_get(table, row_key, col, var_id=var_id, key=key_tuple)
    if t == 'tableLookup':
        table_id = d.get('table')
        row_ref = d.get('row')
        col_sel = d.get('columnSelector')
        table = TABLES.get(table_id) if table_id else None
        if not table:
            return _nan()
        if row_ref:
            row_key = G(row_ref, *[idx.get(a) for a in VAR_DOMAINS.get(row_ref, [])])
        else:
            row_key = idx.get(TEMPORAL_ID)
        if col_sel:
            col_name = G(col_sel, *[idx.get(a) for a in VAR_DOMAINS.get(col_sel, [])])
            return safe_table_get(table, row_key, str(col_name), var_id=var_id, key=key_tuple)
        headers = table.get('headers') or []
        if len(headers) < 2:
            return _nan()
        return safe_table_get(table, row_key, headers[1], var_id=var_id, key=key_tuple)
    return _nan()

def compute_point(idx: Dict[str, Any]) -> None:
    """Compute all variables for this exact index-point (including current temporal step)

    in deterministic topo order, without recursion."""
    # Ensure shifted deps that go out of temporal range are visible as NaN
    for var_id in TOPO_VARS:
        dom = VAR_DOMAINS.get(var_id, [])
        kt = _key_tuple(var_id, idx)
        key = (var_id, kt)
        if key in CACHE:
            continue
        # Pre-mark any shifted dependencies that are out-of-range, so G() sees them deterministically
        for dep in VAR_DEPS.get(var_id, []):
            dep_id = dep.get('name')
            shift = int(dep.get('shift') or 0)
            if not dep_id or dep_id == var_id:
                continue
            dep_dom = VAR_DOMAINS.get(dep_id, [])
            if shift != 0 and TEMPORAL_ID in dep_dom:
                dep_idx = dict(idx)
                tval = dep_idx.get(TEMPORAL_ID)
                if tval is None:
                    continue
                dep_idx[TEMPORAL_ID] = tval + shift
                if dep_idx[TEMPORAL_ID] < TEMP_MIN or dep_idx[TEMPORAL_ID] > TEMP_MAX:
                    dep_type = (VAR_DEFS.get(dep_id) or {}).get('type')
                    if dep_type in ('table', 'tableLookup'):
                        dep_kt = tuple(dep_idx.get(d) for d in dep_dom)
                        dep_key = (dep_id, dep_kt)
                        if dep_key not in CACHE:
                            if not STRICT:
                                _record_error('dep_oob', dep_id, dep_kt, 'out of range', ValueError('temporal index out of bounds'))
                            CACHE[dep_key] = _nan()
                    # For expression/piecewise/constant deps, allow lazy evaluation beyond TEMP_MAX if requested.
        val = compute_value(var_id, idx)
        if val is None:
            val = _nan()
        # If the result is NaN and no specific error was recorded, record nan_result.
        if isinstance(val, float) and math.isnan(val):
            _record_error('nan_result', var_id, kt, 'nan', ValueError('expression evaluated to NaN'))
        CACHE[key] = val

def index_values(indexset_id: str, TEMP_MAX: int, overrides: Dict[str, List[str]]) -> List[Any]:
    # integer ranges if min/max exist; else use overrides or defaults
    meta = next((x for x in INDEXSETS if x.get('id') == indexset_id), None)
    dt = str((meta or {}).get('dataType') or '').lower()
    if indexset_id == TEMPORAL_ID:
        # always 0..TEMP_MAX
        return list(range(0, TEMP_MAX + 1))
    if dt in ('integer', 'int') and meta and meta.get('min') is not None and meta.get('max') is not None:
        try:
            lo = int(float(meta['min']))
            hi = int(float(meta['max']))
            return list(range(lo, hi + 1))
        except Exception:
            pass
    # Prefer overrides from CLI
    if indexset_id in overrides:
        raw = overrides[indexset_id]
        # attempt numeric coercion
        out = []
        for s in raw:
            out.append(_coerce_cell(s))
        return out
    # If any table uses this indexset as its rowIndex, infer values from that table's first column
    for tid, t in TABLES.items():
        hdr = (t.get('headers') or [])
        if hdr and hdr[0] == indexset_id:
            vals = []
            for r in (t.get('rows') or []):
                if r and r[0] not in vals:
                    vals.append(r[0])
            if vals:
                return vals
    # final fallback
    return [1] if indexset_id.lower() == 'cohort' else ['default']

def main() -> None:
    ap = argparse.ArgumentParser(description='Run exported model')
    ap.add_argument('--steps', type=int, default=20, help='temporal max (inclusive)')
    default_csv = _sanitize_filename(MODEL_ID) + '_out.csv'
    ap.add_argument('--csv', type=str, default=default_csv, help='Output CSV path (default: <model_id>_out.csv)')
    ap.add_argument('--index', action='append', default=[], help='Override index values: --index cohort=1,2 or --index day_type=weekday,weekend')
    ap.add_argument('--strict', action='store_true', help='Fail fast on evaluation errors (instead of returning NaN)')
    # ---- Optional plot GIF output ----
    plot_group = ap.add_mutually_exclusive_group()
    plot_group.add_argument('--plot-traj', dest='plot_traj', action='store_true', help='Generate an animated trajectory GIF after computing results (requires --plot-vars)')
    plot_group.add_argument('--plot-static', dest='plot_static', action='store_true', help='Generate a single-frame (static) trajectory GIF after computing results (requires --plot-vars)')
    default_gif = _sanitize_filename(MODEL_ID) + '.gif'
    ap.add_argument('--gif', type=str, default=default_gif, help='GIF output path (default: <model_id>.gif; only used with --plot-traj/--plot-static)')
    ap.add_argument('--fps', type=int, default=24, help='Frames per second for animated GIF (only used with --plot-traj)')
    ap.add_argument('--dpi', type=int, default=120, help='DPI for GIF rendering')
    ap.add_argument('--plot-vars', dest='plot_vars', type=str, default='', help='Plot specification(s). Format: label:x[,y[,z]];label2:x[,y[,z]]. (1D uses t vs x; 2D uses x,y; 3D uses x,y,z).')
    ap.add_argument('--plot-t', dest='plot_t', type=str, default=TEMPORAL_ID, help='Temporal column to animate over for --plot-vars (defaults to temporal index).')
    ap.add_argument('--plot-title', dest='plot_title', type=str, default='', help='Column to display in the plot title (defaults to --plot-t).')
    ap.add_argument('--plot-step', dest='plot_step', type=int, default=1, help='Frame stride for --plot-traj (use >1 to reduce frames).')
    ap.add_argument('--plot-point', dest='plot_point', action='store_true', help='Draw only the moving point (not the whole tail).')
    ap.add_argument('--plot-head-color', dest='plot_head_color', type=str, default='red', help='Default head color for plotted trajectories.')
    ap.add_argument('--plot-tail-color', dest='plot_tail_color', type=str, default='blue', help='Default tail color for plotted trajectories.')
    ap.add_argument('--plot-head-colors', dest='plot_head_colors', type=str, default='', help='Per-trajectory head colors: label=color,label2=color')
    ap.add_argument('--plot-tail-colors', dest='plot_tail_colors', type=str, default='', help='Per-trajectory tail colors: label=color,label2=color')
    ap.add_argument('--no-model-id-title', action='store_true', help='Suppress model id in plot title (saves space)')
    args = ap.parse_args()

    overrides: Dict[str, List[str]] = {}
    for item in args.index:
        if '=' not in item:
            continue
        k, v = item.split('=', 1)
        overrides[k.strip()] = [x.strip() for x in v.split(',') if x.strip() != '']

    base_dir = os.path.dirname(os.path.abspath(__file__))
    global TABLES
    TABLES, _table_sources = load_tables_from_csv(base_dir, DEFAULT_TABLES)
    if _table_sources:
        _log('Input tables:')
        for _tid, _src in sorted(_table_sources.items()):
            if _src == 'embedded':
                _log(f'  {_tid}: using embedded sample data (no input_{_tid}.csv found)')
            else:
                _log(f'  {_tid}: loaded from {_src}')
    global STRICT
    global TEMP_MAX
    STRICT = bool(args.strict)
    TEMP_MAX = int(args.steps)
    # Increase recursion limit for forward/backward temporal recursions  
    import sys  
    try: 
        sys.setrecursionlimit(max(10000, int(TEMP_MAX) + 5000)) 
    except Exception: 
        pass 
    if TEMP_MAX < 0: raise SystemExit('steps must be >= 0')

    # Determine index values for all index sets used by any variable
    used_indexsets = set()
    for dom in VAR_DOMAINS.values():
        for d in dom:
            used_indexsets.add(d)
    idx_vals: Dict[str, List[Any]] = {d: index_values(d, TEMP_MAX, overrides) for d in used_indexsets}

    # ---- Precompute temporal self-recursive variables iteratively (avoid Python recursion) ----
    # A var is 'temporal self-recursive' if it depends on itself with a non-zero temporal shift.
    temporal_self_vars = []
    for _vid, _deps in (VAR_DEPS or {}).items():
        _self = None
        for _d in (_deps or []):
            if _d.get('name') == _vid and int(_d.get('shift') or 0) != 0:
                _self = _d
                break
        if _self is not None and TEMPORAL_ID in (VAR_DOMAINS.get(_vid, []) or []):
            temporal_self_vars.append((_vid, int(_self.get('shift') or 0)))
    
    if temporal_self_vars:
        _steps = idx_vals.get(TEMPORAL_ID, [])
        # For each such variable, iterate over all combinations of its *non-temporal* domain axes,
        # and compute across step in the correct direction:
        #   shift < 0  (uses step-1) => compute forward in time
        #   shift > 0  (uses step+1) => compute backward in time
        def _iter_combos(_axes, _vals, _i, _cur, _out):
            if _i >= len(_axes):
                _out.append(dict(_cur))
                return
            _a = _axes[_i]
            for _v in _vals.get(_a, []):
                _cur[_a] = _v
                _iter_combos(_axes, _vals, _i + 1, _cur, _out)
            _cur.pop(_a, None)
    
        for _vid, _shift in temporal_self_vars:
            _dom = VAR_DOMAINS.get(_vid, []) or []
            _axes = [d for d in _dom if d != TEMPORAL_ID]
            _combos = []
            _iter_combos(_axes, idx_vals, 0, {}, _combos)
            _ordered_steps = _steps if _shift < 0 else list(reversed(_steps))
            for _base in _combos:
                # Seed boundary for forward recursion (shift > 0):
                # If model wants step+shift but our run horizon stops at TEMP_MAX,
                # assume the value just beyond the horizon is 0 (no future beyond run).
                if _shift > 0:
                    for _k in range(1, _shift + 1):
                        _seed = dict(_base)
                        _seed[TEMPORAL_ID] = TEMP_MAX + _k
                        _seed_kt = tuple(_seed.get(d) for d in _dom)
                        _seed_key = (_vid, _seed_kt)
                        if _seed_key not in CACHE:
                            CACHE[_seed_key] = 0
    
                for _t in _ordered_steps:
                    _idx = dict(_base)
                    _idx[TEMPORAL_ID] = _t
                    _kt = tuple(_idx.get(d) for d in _dom)
                    _key = (_vid, _kt)
                    if _key not in CACHE:
                        CACHE[_key] = compute_value_no_self(_vid, _idx)
    
    # Build output columns: all variables (scalar first), then indexed
    # IMPORTANT: compute scalars in deterministic topo order to avoid missing_dep due to alpha ordering
    scalar_vars = [vid for vid in TOPO_VARS if len(VAR_DOMAINS.get(vid, [])) == 0]
    indexed_vars = [vid for vid, dom in VAR_DOMAINS.items() if len(dom) > 0]
    indexed_vars.sort()

    # For CSV output, we emit one row per combination of index values for indexed vars.
    # To keep files manageable, we use the union of domains: one big cartesian product over used_indexsets.
    axis = sorted(list(used_indexsets), key=lambda x: (x != TEMPORAL_ID, x))
    headers = axis + scalar_vars + indexed_vars
    with open(args.csv, 'w', newline='') as f:
        w = csv.writer(f)
        w.writerow(headers)
        # Precompute scalar values once (topo order, no recursion)
        scalar_vals = {}
        for vid in scalar_vars:
            kt = ()
            key = (vid, kt)
            if key not in CACHE:
                CACHE[key] = compute_value(vid, {})
            scalar_vals[vid] = CACHE[key]
        # Cartesian product over axis
        def rec(i: int, cur: Dict[str, Any]):
            if i >= len(axis):
                # Compute all values for this index-point before reading outputs
                compute_point(cur)
                row = [cur.get(a) for a in axis]
                row += [scalar_vals.get(v) for v in scalar_vars]
                for v in indexed_vars:
                    dom = VAR_DOMAINS.get(v, [])
                    kt = tuple(cur.get(d) for d in dom)
                    row.append(CACHE.get((v, kt), float('nan')))
                w.writerow(row)
                return
            a = axis[i]
            for val in idx_vals.get(a, []):
                cur[a] = val
                rec(i + 1, cur)
            cur.pop(a, None)
        rec(0, {})

    _log(f'Encountered {len(ERRORS)} evaluation issue(s)')
    _log(f'Wrote {args.csv}')
    if ERRORS:
        # Emit a compact error report to stderr
        import sys
        _err_hdr = f'\nEncountered {len(ERRORS)} evaluation issue(s). Showing first 20:'
        sys.stderr.write(_err_hdr + '\n')
        _LOG_LINES.append(_err_hdr.strip())
        for e in ERRORS[:20]:
            _err_line = f"- {e['kind']} var={e['var']} idx={e['idx']} expr={e['expr']} err={e['error']}"
            sys.stderr.write(_err_line + '\n')
            _LOG_LINES.append(_err_line)
    log_path = os.path.splitext(args.csv)[0] + '.log'
    _log(f'Log written to {log_path}')
    with open(log_path, 'w') as _lf:
        _lf.write('\n'.join(_LOG_LINES) + '\n')

    # ---- Plot GIF (optional) ----
    plot_traj = bool(getattr(args, 'plot_traj', False))
    plot_static = bool(getattr(args, 'plot_static', False))
    if plot_traj or plot_static:
        plot_vars = str(getattr(args, 'plot_vars', '')).strip()
        if not plot_vars:
            print('Plot requested but --plot-vars not provided; skipping plot.')
        else:
            try:
                import pandas as pd
                import matplotlib.pyplot as plt
                from matplotlib.animation import FuncAnimation, PillowWriter
            except Exception as e:
                raise SystemExit('Trajectory plotting requires pandas, matplotlib, and Pillow. ' + repr(e))

            # Read only header first (fast) to discover columns, then load only needed columns.
            _all_cols = pd.read_csv(args.csv, nrows=0).columns.tolist()
            df = None  # will be loaded after parsing plot spec
            tcol = str(getattr(args, 'plot_t', TEMPORAL_ID)).strip() or TEMPORAL_ID
            title_col = str(getattr(args, 'plot_title', '')).strip() or tcol
            if title_col not in _all_cols:
                raise SystemExit(f'Title column {title_col} not found. Available: {_all_cols}')
            step = max(1, int(getattr(args, 'plot_step', 1)))
            point_only = bool(getattr(args, 'plot_point', False))
            default_head = str(getattr(args, 'plot_head_color', 'red'))
            default_tail = str(getattr(args, 'plot_tail_color', 'blue'))

            if tcol not in _all_cols:
                raise SystemExit(f'Temporal column {tcol} not found. Available: {_all_cols}')

            def _parse_color_map(s: str):
                out = {}
                s = (s or '').strip()
                if not s: return out
                for item in s.split(','):
                    item = item.strip()
                    if not item or '=' not in item: continue
                    k, v = item.split('=', 1)
                    out[k.strip()] = v.strip()
                return out

            head_map = _parse_color_map(str(getattr(args, 'plot_head_colors', '')))
            tail_map = _parse_color_map(str(getattr(args, 'plot_tail_colors', '')))

            def _parse_trajs(spec: str):
                items = [p.strip() for p in spec.split(';') if p.strip()]
                out = []
                for it in items:
                    if ':' in it:
                        label, rhs = it.split(':', 1)
                        label = (label.strip() or 'traj')
                    else:
                        label, rhs = ('traj', it)
                    parts = [q.strip() for q in rhs.split(',') if q.strip()]
                    if len(parts) < 1 or len(parts) > 3:
                        raise SystemExit('Each trajectory must have 1 to 3 coordinates: x[,y[,z]]')
                    out.append((label, parts))
                return out

            trajs = _parse_trajs(plot_vars)

            def _parse_trajs(spec: str):
                items = [p.strip() for p in spec.split(';') if p.strip()]
                out = []
                for it in items:
                    if ':' in it:
                        label, rhs = it.split(':', 1)
                        label = (label.strip() or 'traj')
                    else:
                        label, rhs = ('traj', it)
                    parts = [q.strip() for q in rhs.split(',') if q.strip()]
                    if len(parts) < 1 or len(parts) > 3:
                        raise SystemExit('Each trajectory must have 1 to 3 coordinates: x[,y[,z]]')
                    out.append((label, parts))
                return out

            trajs = _parse_trajs(plot_vars)
            dims = sorted(set(len(parts) for _, parts in trajs))
            if len(dims) != 1:
                raise SystemExit(f'All trajectories must have the same dimensionality (got {dims}). Use z=0 for 2D in 3D, or provide only x for 1D.')
            dim = dims[0]

            _need = {tcol, title_col}
            # If user provided --index filters and those columns exist in the CSV, load them too so we can filter before plotting
            for _k in overrides.keys():
                if _k in _all_cols:
                    _need.add(_k)
            for _label, _parts in trajs:
                for _c in _parts:
                    if _c in _all_cols: _need.add(_c)
            df = pd.read_csv(args.csv, usecols=sorted(_need))

            # Apply --index filters to the plotting dataframe (so plots reflect the same cohort/index slice)
            # This also avoids silently taking the 'first' row when multiple index combinations exist per step.
            def _coerce_override_list(vs):
                out = []
                for s in vs:
                    try:
                        out.append(_coerce_cell(s))
                    except Exception:
                        out.append(s)
                return out
            for _k, _vs in overrides.items():
                if _k in df.columns and _k != tcol:
                    _vals = _coerce_override_list(_vs)
                    if len(_vals) == 1:
                        df = df[df[_k] == _vals[0]]
                    elif len(_vals) > 1:
                        df = df[df[_k].isin(_vals)]

            traj_data = []
            frames = None
            for label, parts in trajs:
                cols = [tcol] + parts
                if title_col not in cols: cols.append(title_col)
                for c in cols:
                    if c != tcol and c not in _all_cols:
                        try: float(c)
                        except Exception: raise SystemExit(f'Column {c} not found. Available: {_all_cols}')
                dd = df[[c for c in cols if c in df.columns]].copy()
                for c in parts:
                    if c not in dd.columns:
                        dd[c] = float(c)
                # Keep title_col too (so we can label frames nicely)
                keep_cols = [tcol] + parts + ([title_col] if title_col not in ([tcol] + parts) else [])
                keep_cols = list(dict.fromkeys(keep_cols))  # dedupe columns
                dd = dd[keep_cols].dropna().sort_values(tcol)
                dd = dd.groupby(tcol, as_index=False).first()
                if dd.empty: raise SystemExit(f'No data for trajectory {label}')
                if frames is None:
                    frames = dd[tcol].tolist()
                else:
                    dd = dd[dd[tcol].isin(frames)]
                traj_data.append((label, dd, parts))

            frames = traj_data[0][1][tcol].tolist()
            if not frames: raise SystemExit('No frames found')

            # Frame selection:
            frames = traj_data[0][1][tcol].tolist()
            if not frames: raise SystemExit('No frames found')
            frame_idx = list(range(0, len(frames), step))
            if frame_idx[-1] != len(frames) - 1: frame_idx.append(len(frames) - 1)
            if plot_static: frame_idx = [len(frames) - 1]

            out_gif = str(getattr(args, 'gif', 'model.gif'))
            fps = int(getattr(args, 'fps', 24))
            dpi = int(getattr(args, 'dpi', 120))

            if dim == 3:
                from mpl_toolkits.mplot3d import Axes3D  # noqa: F401
                fig = plt.figure()
                ax = fig.add_subplot(111, projection='3d')
            else:
                fig, ax = plt.subplots()

            if dim == 1:
                t_min, t_max = float(min(frames)), float(max(frames))
                y_min = min(float(dd[parts[0]].min()) for _, dd, parts in traj_data)
                y_max = max(float(dd[parts[0]].max()) for _, dd, parts in traj_data)
            elif dim == 2:
                x_min = min(float(dd[parts[0]].min()) for _, dd, parts in traj_data)
                x_max = max(float(dd[parts[0]].max()) for _, dd, parts in traj_data)
                y_min = min(float(dd[parts[1]].min()) for _, dd, parts in traj_data)
                y_max = max(float(dd[parts[1]].max()) for _, dd, parts in traj_data)
            else:
                x_min = min(float(dd[parts[0]].min()) for _, dd, parts in traj_data)
                x_max = max(float(dd[parts[0]].max()) for _, dd, parts in traj_data)
                y_min = min(float(dd[parts[1]].min()) for _, dd, parts in traj_data)
                y_max = max(float(dd[parts[1]].max()) for _, dd, parts in traj_data)
                z_min = min(float(dd[parts[2]].min()) for _, dd, parts in traj_data)
                z_max = max(float(dd[parts[2]].max()) for _, dd, parts in traj_data)

            def draw(i):
                ax.clear()
                j = frame_idx[i]
                t_now = frames[j]
                title_now = traj_data[0][1].iloc[j][title_col] if title_col in traj_data[0][1].columns else t_now
                for label, dd, parts in traj_data:
                    tail_color = tail_map.get(label, default_tail)
                    head_color = head_map.get(label, default_head)
                    seg = dd.iloc[[j]] if point_only else dd.iloc[: j + 1]
                    if dim == 1:
                        if not point_only: ax.plot(seg[tcol].values, seg[parts[0]].values, color=tail_color, linewidth=2, label=label)
                        ax.scatter([dd.iloc[j][tcol]], [dd.iloc[j][parts[0]]], color=head_color, s=60)
                    elif dim == 2:
                        if not point_only: ax.plot(seg[parts[0]].values, seg[parts[1]].values, color=tail_color, linewidth=2, label=label)
                        ax.scatter([dd.iloc[j][parts[0]]], [dd.iloc[j][parts[1]]], color=head_color, s=60)
                    else:
                        if not point_only: ax.plot(seg[parts[0]].values, seg[parts[1]].values, seg[parts[2]].values, color=tail_color, linewidth=2, label=label)
                        ax.scatter([dd.iloc[j][parts[0]]], [dd.iloc[j][parts[1]]], [dd.iloc[j][parts[2]]], color=head_color, s=60)
                if dim == 1:
                    ax.set_xlabel(tcol); ax.set_ylabel(traj_data[0][2][0]); ax.set_xlim(t_min, t_max); ax.set_ylim(y_min, y_max)
                elif dim == 2:
                    ax.set_xlabel(traj_data[0][2][0]); ax.set_ylabel(traj_data[0][2][1]); ax.set_xlim(x_min, x_max); ax.set_ylim(y_min, y_max)
                else:
                    ax.set_xlabel(traj_data[0][2][0]); ax.set_ylabel(traj_data[0][2][1]); ax.set_zlabel(traj_data[0][2][2]); ax.set_xlim(x_min, x_max); ax.set_ylim(y_min, y_max); ax.set_zlim(z_min, z_max)
                try: ax.legend(loc='upper right', fontsize='small')
                except Exception: pass
                if bool(getattr(args, 'no_model_id_title', False)):
                    ax.set_title(f'{title_col}={title_now}')
                else:
                    ax.set_title(f'{MODEL_ID} | {title_col}={title_now}')

            ani = FuncAnimation(fig, draw, frames=len(frame_idx), interval=1000 / max(1, fps), repeat=False)
            ani.save(out_gif, writer=PillowWriter(fps=fps), dpi=dpi)
            plt.close(fig)
            print(f'Saved trajectory GIF to {out_gif}')
if __name__ == '__main__':
    main()